-- UniAdmSys: candidate + staff workflow + floor score
-- Minimal schema for applicant data, staff accounts, preferences and score comparison.
-- Admission pass/fail is NOT stored. The web/backend compares calculated scores
-- against cutoff scores when needed.

BEGIN;

-- =========================================================
-- 1) STAFF / MANAGEMENT ACCOUNTS
-- Authentication should be handled by Supabase Auth.
-- user_id links a staff profile to auth.users when an account is created.
-- No password is stored in this table.
-- =========================================================
CREATE TABLE IF NOT EXISTS public.can_bo (
    ma_can_bo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID UNIQUE,
    ten_dang_nhap VARCHAR(80) UNIQUE NOT NULL,
    ho_ten VARCHAR(150) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    so_dien_thoai VARCHAR(30),
    don_vi VARCHAR(150),
    chuc_vu VARCHAR(100),
    vai_tro VARCHAR(30) NOT NULL DEFAULT 'can_bo',
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'hoat_dong',
    lan_dang_nhap_cuoi TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT can_bo_vai_tro_check
        CHECK (vai_tro IN ('quan_ly', 'can_bo')),
    CONSTRAINT can_bo_trang_thai_check
        CHECK (trang_thai IN ('hoat_dong', 'tam_khoa'))
);

-- Patch an older can_bo table if it already exists.
ALTER TABLE public.can_bo
    ADD COLUMN IF NOT EXISTS user_id UUID,
    ADD COLUMN IF NOT EXISTS ten_dang_nhap VARCHAR(80),
    ADD COLUMN IF NOT EXISTS ho_ten VARCHAR(150),
    ADD COLUMN IF NOT EXISTS email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS so_dien_thoai VARCHAR(30),
    ADD COLUMN IF NOT EXISTS don_vi VARCHAR(150),
    ADD COLUMN IF NOT EXISTS chuc_vu VARCHAR(100),
    ADD COLUMN IF NOT EXISTS vai_tro VARCHAR(30) DEFAULT 'can_bo',
    ADD COLUMN IF NOT EXISTS trang_thai VARCHAR(30) DEFAULT 'hoat_dong',
    ADD COLUMN IF NOT EXISTS lan_dang_nhap_cuoi TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS idx_can_bo_user_id
ON public.can_bo(user_id)
WHERE user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_can_bo_ten_dang_nhap
ON public.can_bo(ten_dang_nhap)
WHERE ten_dang_nhap IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_can_bo_email
ON public.can_bo(email)
WHERE email IS NOT NULL;

-- =========================================================
-- 2) APPLICANTS
-- =========================================================
CREATE TABLE IF NOT EXISTS public.thi_sinh (
    ma_thi_sinh BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID UNIQUE,
    cccd VARCHAR(20) UNIQUE,
    ho_ten VARCHAR(150) NOT NULL,
    ngay_sinh DATE,
    gioi_tinh VARCHAR(20),
    tinh_thanh VARCHAR(100),
    so_dien_thoai VARCHAR(30),
    email VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_thi_sinh_email
ON public.thi_sinh(email);

-- =========================================================
-- 3) EXAM SCORES
-- One row per applicant / year / subject.
-- =========================================================
CREATE TABLE IF NOT EXISTS public.diem_thi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_thi_sinh BIGINT NOT NULL
        REFERENCES public.thi_sinh(ma_thi_sinh) ON DELETE CASCADE,
    nam SMALLINT NOT NULL,
    mon_thi VARCHAR(100) NOT NULL,
    diem NUMERIC(5,2),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    CONSTRAINT diem_thi_range CHECK (diem IS NULL OR (diem >= 0 AND diem <= 10))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_diem_thi_unique
ON public.diem_thi(ma_thi_sinh, nam, mon_thi);

CREATE INDEX IF NOT EXISTS idx_diem_thi_thi_sinh
ON public.diem_thi(ma_thi_sinh, nam);

-- =========================================================
-- 4) ADMISSION PREFERENCES
-- =========================================================
CREATE TABLE IF NOT EXISTS public.nguyen_vong (
    ma_nv BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_thi_sinh BIGINT NOT NULL
        REFERENCES public.thi_sinh(ma_thi_sinh) ON DELETE CASCADE,
    ma_nganh VARCHAR(20) NOT NULL
        REFERENCES public.nganh(ma_nganh) ON DELETE RESTRICT,
    nam SMALLINT NOT NULL DEFAULT 2025,
    ma_phuong_thuc VARCHAR(20),
    ma_to_hop VARCHAR(20)
        REFERENCES public.to_hop_xet_tuyen(ma_to_hop) ON DELETE SET NULL,
    thu_tu_nguyen_vong INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    CONSTRAINT nguyen_vong_thu_tu_positive CHECK (thu_tu_nguyen_vong > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_nguyen_vong_unique_order
ON public.nguyen_vong(ma_thi_sinh, nam, thu_tu_nguyen_vong);

CREATE INDEX IF NOT EXISTS idx_nguyen_vong_lookup
ON public.nguyen_vong(ma_thi_sinh, nam, ma_nganh);

-- =========================================================
-- 5) ADMISSION RESULT / CALCULATED SCORE
-- No pass/fail status is stored.
-- The application compares diem_xet_tuyen with public.diem_chuan.
-- =========================================================
CREATE TABLE IF NOT EXISTS public.ket_qua_xet_tuyen (
    ma_kq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_thi_sinh BIGINT NOT NULL
        REFERENCES public.thi_sinh(ma_thi_sinh) ON DELETE CASCADE,
    ma_nv BIGINT NOT NULL
        REFERENCES public.nguyen_vong(ma_nv) ON DELETE CASCADE,
    diem_xet_tuyen NUMERIC(6,2),
    ghi_chu TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

-- Migrate the previous version if it contained a stored pass/fail state.
ALTER TABLE public.ket_qua_xet_tuyen
    DROP CONSTRAINT IF EXISTS ket_qua_trang_thai_check;

ALTER TABLE public.ket_qua_xet_tuyen
    DROP COLUMN IF EXISTS trang_thai;

ALTER TABLE public.ket_qua_xet_tuyen
    ADD COLUMN IF NOT EXISTS diem_xet_tuyen NUMERIC(6,2),
    ADD COLUMN IF NOT EXISTS ghi_chu TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS idx_ket_qua_xet_tuyen_nv
ON public.ket_qua_xet_tuyen(ma_nv);

CREATE INDEX IF NOT EXISTS idx_ket_qua_xet_tuyen_thi_sinh
ON public.ket_qua_xet_tuyen(ma_thi_sinh);

-- =========================================================
-- 6) FLOOR SCORE / ENTRY THRESHOLD
-- A floor score is one threshold value, separate from tuition.
-- =========================================================
CREATE TABLE IF NOT EXISTS public.nguong_dau_vao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_truong VARCHAR(20) NOT NULL
        REFERENCES public.truong_dh(ma_tuyen_sinh)
        ON DELETE CASCADE,
    nam SMALLINT NOT NULL DEFAULT 2025,
    ma_nganh VARCHAR(20)
        REFERENCES public.nganh(ma_nganh)
        ON DELETE CASCADE,
    ma_phuong_thuc VARCHAR(20)
        REFERENCES public.phuong_thuc_xet_tuyen(ma_phuong_thuc)
        ON DELETE SET NULL,
    diem_san NUMERIC(8,2),
    trang_thai VARCHAR(30) DEFAULT 'chua_xac_minh',
    ghi_chu TEXT,
    source_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_nguong_dau_vao_school_level
ON public.nguong_dau_vao(
    ma_truong,
    nam,
    COALESCE(ma_nganh,''),
    COALESCE(ma_phuong_thuc,'')
);

-- =========================================================
-- 7) UPDATE PUBLIC VIEWS
-- =========================================================
CREATE OR REPLACE VIEW public.v_truong_tuyen_sinh_2025 AS
SELECT
    t.ma_truong AS id_truong,
    t.ma_tuyen_sinh,
    t.ten_truong,

    h.hoc_phi_min,
    h.hoc_phi_max,
    h.don_vi AS hoc_phi_don_vi,
    h.trang_thai AS hoc_phi_trang_thai,
    h.source_url AS hoc_phi_source_url,

    c.chi_tieu,
    c.chi_tieu_min,
    c.chi_tieu_max,
    c.trang_thai AS chi_tieu_trang_thai,
    c.source_url AS chi_tieu_source_url,

    ndv.diem_san,
    ndv.trang_thai AS diem_san_trang_thai,
    ndv.ghi_chu AS diem_san_ghi_chu,
    ndv.source_url AS diem_san_source_url

FROM public.truong_dh t
LEFT JOIN public.hoc_phi h
    ON h.ma_truong = t.ma_tuyen_sinh
   AND h.nam = 2025
LEFT JOIN public.chi_tieu_tuyen_sinh c
    ON c.ma_truong = t.ma_tuyen_sinh
   AND c.nam = 2025
   AND COALESCE(c.cap_do, 'truong') = 'truong'
LEFT JOIN public.nguong_dau_vao ndv
    ON ndv.ma_truong = t.ma_tuyen_sinh
   AND ndv.nam = 2025
   AND ndv.ma_nganh IS NULL
   AND ndv.ma_phuong_thuc IS NULL;

CREATE OR REPLACE VIEW public.v_catalog_tuyen_sinh_2025 AS
SELECT
    n.ma_nganh,
    n.ma_truong,
    n.ten_truong,
    n.ma_nganh_tuyen_sinh,
    n.ten_nganh,
    n.ma_nganh_bo,
    n.ten_nganh_bo,

    h.hoc_phi_min,
    h.hoc_phi_max,
    h.hoc_phi_don_vi,
    h.hoc_phi_trang_thai,

    h.chi_tieu,
    h.chi_tieu_min,
    h.chi_tieu_max,
    h.chi_tieu_trang_thai,

    h.diem_san,
    h.diem_san_trang_thai,
    h.diem_san_ghi_chu,
    h.diem_san_source_url

FROM public.v_nganh_2025 n
LEFT JOIN public.v_truong_tuyen_sinh_2025 h
    ON h.ma_tuyen_sinh = n.ma_truong;


-- =========================================================
-- 8) RLS
-- Private user/staff tables remain backend-only for now.
-- service_role bypasses RLS.
-- =========================================================
ALTER TABLE public.can_bo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.thi_sinh ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diem_thi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nguyen_vong ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ket_qua_xet_tuyen ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.can_bo FROM anon, authenticated;
REVOKE ALL ON TABLE public.thi_sinh FROM anon, authenticated;
REVOKE ALL ON TABLE public.diem_thi FROM anon, authenticated;
REVOKE ALL ON TABLE public.nguyen_vong FROM anon, authenticated;
REVOKE ALL ON TABLE public.ket_qua_xet_tuyen FROM anon, authenticated;

COMMIT;

-- QA
SELECT
    to_regclass('public.can_bo') AS can_bo,
    to_regclass('public.thi_sinh') AS thi_sinh,
    to_regclass('public.diem_thi') AS diem_thi,
    to_regclass('public.nguyen_vong') AS nguyen_vong,
    to_regclass('public.ket_qua_xet_tuyen') AS ket_qua_xet_tuyen;

SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'hoc_phi'
  AND column_name LIKE 'diem_san%'
ORDER BY ordinal_position;
