-- UniAdmSys: special admission achievements + certificate conversion
-- Stores configurable rules by university/year. Does not assume one universal conversion table.

BEGIN;

CREATE TABLE IF NOT EXISTS public.thanh_tich_chung_chi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_thi_sinh BIGINT NOT NULL REFERENCES public.thi_sinh(ma_thi_sinh) ON DELETE CASCADE,
    nhom VARCHAR(30) NOT NULL CHECK (nhom IN ('thanh_tich','chung_chi')),
    loai VARCHAR(60) NOT NULL,
    ten TEXT NOT NULL,
    mon_linh_vuc VARCHAR(150),
    cap_giai VARCHAR(100),
    thu_hang_giai SMALLINT,
    diem_so NUMERIC(8,2),
    thang_diem VARCHAR(50),
    don_vi_cap VARCHAR(200),
    ngay_cap DATE,
    ngay_het_han DATE,
    minh_chung_url TEXT,
    trang_thai_xac_minh VARCHAR(30) NOT NULL DEFAULT 'chua_xac_minh'
        CHECK (trang_thai_xac_minh IN ('chua_xac_minh','da_xac_minh','tu_choi')),
    ma_can_bo_xac_minh BIGINT REFERENCES public.can_bo(ma_can_bo) ON DELETE SET NULL,
    xac_minh_luc TIMESTAMP WITH TIME ZONE,
    ghi_chu TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_thanh_tich_thi_sinh
ON public.thanh_tich_chung_chi(ma_thi_sinh);

CREATE INDEX IF NOT EXISTS idx_thanh_tich_loai
ON public.thanh_tich_chung_chi(loai);

CREATE TABLE IF NOT EXISTS public.dieu_kien_xet_tuyen_thang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_truong VARCHAR(20) NOT NULL,
    nam SMALLINT NOT NULL DEFAULT 2025,
    ma_nganh VARCHAR(20) REFERENCES public.nganh(ma_nganh) ON DELETE CASCADE,
    ma_phuong_thuc VARCHAR(20),
    loai_thanh_tich VARCHAR(60) NOT NULL,
    mon_linh_vuc VARCHAR(150),
    giai_toi_da SMALLINT,
    xet_tuyen_thang BOOLEAN NOT NULL DEFAULT true,
    uu_tien_xet_tuyen BOOLEAN NOT NULL DEFAULT false,
    ghi_chu TEXT,
    source_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_xet_tuyen_thang_lookup
ON public.dieu_kien_xet_tuyen_thang(ma_truong, nam, ma_nganh, loai_thanh_tich);

CREATE TABLE IF NOT EXISTS public.quy_doi_chung_chi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_truong VARCHAR(20) NOT NULL,
    nam SMALLINT NOT NULL DEFAULT 2025,
    ma_nganh VARCHAR(20) REFERENCES public.nganh(ma_nganh) ON DELETE CASCADE,
    ma_phuong_thuc VARCHAR(20),
    loai_chung_chi VARCHAR(60) NOT NULL,
    diem_tu NUMERIC(8,2) NOT NULL,
    diem_den NUMERIC(8,2),
    diem_quy_doi NUMERIC(8,2) NOT NULL,
    thang_diem_quy_doi VARCHAR(50) DEFAULT '10',
    ghi_chu TEXT,
    source_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT quy_doi_range_check CHECK (diem_den IS NULL OR diem_den >= diem_tu)
);

CREATE INDEX IF NOT EXISTS idx_quy_doi_chung_chi_lookup
ON public.quy_doi_chung_chi(ma_truong, nam, loai_chung_chi, diem_tu);

CREATE OR REPLACE VIEW public.v_chung_chi_quy_doi AS
SELECT
    cc.id AS minh_chung_id,
    cc.ma_thi_sinh,
    cc.loai AS loai_chung_chi,
    cc.ten,
    cc.diem_so,
    q.id AS quy_tac_id,
    q.ma_truong,
    q.nam,
    q.ma_nganh,
    q.ma_phuong_thuc,
    q.diem_quy_doi,
    q.thang_diem_quy_doi,
    q.source_url
FROM public.thanh_tich_chung_chi cc
JOIN public.quy_doi_chung_chi q
  ON q.loai_chung_chi = cc.loai
 AND q.is_active = true
 AND cc.nhom = 'chung_chi'
 AND cc.trang_thai_xac_minh = 'da_xac_minh'
 AND cc.diem_so IS NOT NULL
 AND cc.diem_so >= q.diem_tu
 AND (q.diem_den IS NULL OR cc.diem_so <= q.diem_den);

CREATE OR REPLACE VIEW public.v_xet_tuyen_thang_kha_dung AS
SELECT
    cc.id AS minh_chung_id,
    cc.ma_thi_sinh,
    cc.loai AS loai_thanh_tich,
    cc.ten,
    cc.mon_linh_vuc,
    cc.cap_giai,
    cc.thu_hang_giai,
    r.id AS quy_tac_id,
    r.ma_truong,
    r.nam,
    r.ma_nganh,
    r.ma_phuong_thuc,
    r.xet_tuyen_thang,
    r.uu_tien_xet_tuyen,
    r.ghi_chu,
    r.source_url
FROM public.thanh_tich_chung_chi cc
JOIN public.dieu_kien_xet_tuyen_thang r
  ON r.loai_thanh_tich = cc.loai
 AND r.is_active = true
 AND cc.nhom = 'thanh_tich'
 AND cc.trang_thai_xac_minh = 'da_xac_minh'
 AND (r.mon_linh_vuc IS NULL OR lower(trim(r.mon_linh_vuc)) = lower(trim(cc.mon_linh_vuc)))
 AND (r.giai_toi_da IS NULL OR (cc.thu_hang_giai IS NOT NULL AND cc.thu_hang_giai <= r.giai_toi_da));

ALTER TABLE public.thanh_tich_chung_chi ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.thanh_tich_chung_chi FROM anon, authenticated;

ALTER TABLE public.dieu_kien_xet_tuyen_thang ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS public_read ON public.dieu_kien_xet_tuyen_thang;
CREATE POLICY public_read ON public.dieu_kien_xet_tuyen_thang
FOR SELECT TO anon, authenticated USING (true);
GRANT SELECT ON public.dieu_kien_xet_tuyen_thang TO anon, authenticated;

ALTER TABLE public.quy_doi_chung_chi ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS public_read ON public.quy_doi_chung_chi;
CREATE POLICY public_read ON public.quy_doi_chung_chi
FOR SELECT TO anon, authenticated USING (true);
GRANT SELECT ON public.quy_doi_chung_chi TO anon, authenticated;

ALTER VIEW public.v_chung_chi_quy_doi SET (security_invoker = true);
ALTER VIEW public.v_xet_tuyen_thang_kha_dung SET (security_invoker = true);

COMMIT;

SELECT
    to_regclass('public.thanh_tich_chung_chi') AS thanh_tich_chung_chi,
    to_regclass('public.dieu_kien_xet_tuyen_thang') AS dieu_kien_xet_tuyen_thang,
    to_regclass('public.quy_doi_chung_chi') AS quy_doi_chung_chi;
