-- UniAdmSys: candidate workflow + floor score
-- Adds a minimal applicant flow and keeps floor-score data inside hoc_phi
-- so the public schema stays compact.

BEGIN;

-- =========================================================
-- 1) APPLICANTS
-- =========================================================
CREATE TABLE IF NOT EXISTS public.thi_sinh (
    ma_thi_sinh BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID UNIQUE,
    cccd VARCHAR(20) UNIQUE,
    ho_ten VARCHAR(150) NOT NULL,
    ngay_sinh DATE,
    gioi_tinh VARCHAR(20),
    tinh_thanh VARCHAR(100),
    so_dien_thoai VARCHAR(30),
    email VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

-- =========================================================
-- 2) EXAM SCORES
-- One row per applicant / year / subject.
-- =========================================================
CREATE TABLE IF NOT EXISTS public.diem_thi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_thi_sinh BIGINT NOT NULL
        REFERENCES public.thi_sinh(ma_thi_sinh) ON DELETE CASCADE,
    nam SMALLINT NOT NULL,
    mon_thi VARCHAR(100) NOT NULL,
    diem NUMERIC(5,2),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    CONSTRAINT diem_thi_range CHECK (diem IS NULL OR (diem >= 0 AND diem <= 10))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_diem_thi_unique
ON public.diem_thi(ma_thi_sinh, nam, mon_thi);

CREATE INDEX IF NOT EXISTS idx_diem_thi_thi_sinh
ON public.diem_thi(ma_thi_sinh, nam);

-- =========================================================
-- 3) ADMISSION PREFERENCES
-- =========================================================
CREATE TABLE IF NOT EXISTS public.nguyen_vong (
    ma_nv BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_thi_sinh BIGINT NOT NULL
        REFERENCES public.thi_sinh(ma_thi_sinh) ON DELETE CASCADE,
    ma_nganh VARCHAR(20) NOT NULL
        REFERENCES public.nganh(ma_nganh) ON DELETE RESTRICT,
    nam SMALLINT NOT NULL DEFAULT 2025,
    ma_phuong_thuc VARCHAR(20),
    ma_to_hop VARCHAR(20)
        REFERENCES public.to_hop_xet_tuyen(ma_to_hop) ON DELETE SET NULL,
    thu_tu_nguyen_vong INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    CONSTRAINT nguyen_vong_thu_tu_positive CHECK (thu_tu_nguyen_vong > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_nguyen_vong_unique_order
ON public.nguyen_vong(ma_thi_sinh, nam, thu_tu_nguyen_vong);

CREATE INDEX IF NOT EXISTS idx_nguyen_vong_lookup
ON public.nguyen_vong(ma_thi_sinh, nam, ma_nganh);

-- =========================================================
-- 4) ADMISSION RESULTS
-- One result per preference.
-- =========================================================
CREATE TABLE IF NOT EXISTS public.ket_qua_xet_tuyen (
    ma_kq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_thi_sinh BIGINT NOT NULL
        REFERENCES public.thi_sinh(ma_thi_sinh) ON DELETE CASCADE,
    ma_nv BIGINT NOT NULL
        REFERENCES public.nguyen_vong(ma_nv) ON DELETE CASCADE,
    diem_xet_tuyen NUMERIC(6,2),
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'cho_xet',
    ghi_chu TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    CONSTRAINT ket_qua_trang_thai_check
        CHECK (trang_thai IN ('cho_xet', 'trung_tuyen', 'khong_trung_tuyen', 'da_xac_nhan'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ket_qua_xet_tuyen_nv
ON public.ket_qua_xet_tuyen(ma_nv);

CREATE INDEX IF NOT EXISTS idx_ket_qua_xet_tuyen_thi_sinh
ON public.ket_qua_xet_tuyen(ma_thi_sinh);

-- =========================================================
-- 5) MERGE FLOOR SCORE INTO HOC_PHI
-- Floor-score fields are intentionally nullable until verified.
-- =========================================================
ALTER TABLE public.hoc_phi
    ADD COLUMN IF NOT EXISTS diem_san_min NUMERIC(6,2),
    ADD COLUMN IF NOT EXISTS diem_san_max NUMERIC(6,2),
    ADD COLUMN IF NOT EXISTS diem_san_trang_thai VARCHAR(30) DEFAULT 'chua_xac_minh',
    ADD COLUMN IF NOT EXISTS diem_san_ghi_chu TEXT,
    ADD COLUMN IF NOT EXISTS diem_san_source_url TEXT;

-- =========================================================
-- 6) UPDATE PUBLIC VIEWS
-- Add new columns at the end to preserve existing view columns.
-- =========================================================
CREATE OR REPLACE VIEW public.v_truong_tuyen_sinh_2025 AS
SELECT
    t.ma_truong AS id_truong,
    t.ma_tuyen_sinh,
    t.ten_truong,

    h.hoc_phi_min,
    h.hoc_phi_max,
    h.don_vi AS hoc_phi_don_vi,
    h.trang_thai AS hoc_phi_trang_thai,
    h.source_url AS hoc_phi_source_url,

    c.chi_tieu,
    c.chi_tieu_min,
    c.chi_tieu_max,
    c.trang_thai AS chi_tieu_trang_thai,
    c.source_url AS chi_tieu_source_url,

    h.diem_san_min,
    h.diem_san_max,
    h.diem_san_trang_thai,
    h.diem_san_ghi_chu,
    h.diem_san_source_url

FROM public.truong_dh t
LEFT JOIN public.hoc_phi h
    ON h.ma_truong = t.ma_tuyen_sinh
   AND h.nam = 2025
LEFT JOIN public.chi_tieu_tuyen_sinh c
    ON c.ma_truong = t.ma_tuyen_sinh
   AND c.nam = 2025
   AND COALESCE(c.cap_do, 'truong') = 'truong';

CREATE OR REPLACE VIEW public.v_catalog_tuyen_sinh_2025 AS
SELECT
    n.ma_nganh,
    n.ma_truong,
    n.ten_truong,
    n.ma_nganh_tuyen_sinh,
    n.ten_nganh,
    n.ma_nganh_bo,
    n.ten_nganh_bo,

    h.hoc_phi_min,
    h.hoc_phi_max,
    h.hoc_phi_don_vi,
    h.hoc_phi_trang_thai,

    h.chi_tieu,
    h.chi_tieu_min,
    h.chi_tieu_max,
    h.chi_tieu_trang_thai,

    h.diem_san_min,
    h.diem_san_max,
    h.diem_san_trang_thai,
    h.diem_san_ghi_chu,
    h.diem_san_source_url

FROM public.v_nganh_2025 n
LEFT JOIN public.v_truong_tuyen_sinh_2025 h
    ON h.ma_tuyen_sinh = n.ma_truong;

-- =========================================================
-- 7) RLS
-- Private applicant tables are not directly exposed to clients yet.
-- Backend service_role can still access them.
-- =========================================================
ALTER TABLE public.thi_sinh ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diem_thi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nguyen_vong ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ket_qua_xet_tuyen ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.thi_sinh FROM anon, authenticated;
REVOKE ALL ON TABLE public.diem_thi FROM anon, authenticated;
REVOKE ALL ON TABLE public.nguyen_vong FROM anon, authenticated;
REVOKE ALL ON TABLE public.ket_qua_xet_tuyen FROM anon, authenticated;

COMMIT;

-- QA
SELECT
    to_regclass('public.thi_sinh') AS thi_sinh,
    to_regclass('public.diem_thi') AS diem_thi,
    to_regclass('public.nguyen_vong') AS nguyen_vong,
    to_regclass('public.ket_qua_xet_tuyen') AS ket_qua_xet_tuyen;

SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'hoc_phi'
  AND column_name LIKE 'diem_san%'
ORDER BY ordinal_position;
