-- UniAdmSys: schema hardening for project review
-- Normalizes the admission workflow and closes the most obvious integrity/security gaps.
-- Run AFTER the current candidate/special-admission scripts.

BEGIN;

-- =========================================================
-- 1) NORMALIZE SUBJECTS
-- =========================================================
CREATE TABLE IF NOT EXISTS public.mon_thi (
    ma_mon VARCHAR(20) PRIMARY KEY,
    ten_mon VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO public.mon_thi(ma_mon, ten_mon) VALUES
('TOAN','Toán'),
('VAN','Ngữ văn'),
('ANH','Tiếng Anh'),
('LY','Vật lý'),
('HOA','Hóa học'),
('SINH','Sinh học'),
('SU','Lịch sử'),
('DIA','Địa lý'),
('GDKT_PL','Giáo dục kinh tế và pháp luật')
ON CONFLICT (ma_mon) DO UPDATE SET ten_mon = EXCLUDED.ten_mon;

ALTER TABLE public.diem_thi
    ADD COLUMN IF NOT EXISTS ma_mon VARCHAR(20);

UPDATE public.diem_thi
SET ma_mon = CASE trim(mon_thi)
    WHEN 'Toán' THEN 'TOAN'
    WHEN 'Ngữ văn' THEN 'VAN'
    WHEN 'Tiếng Anh' THEN 'ANH'
    WHEN 'Vật lý' THEN 'LY'
    WHEN 'Hóa học' THEN 'HOA'
    WHEN 'Sinh học' THEN 'SINH'
    WHEN 'Lịch sử' THEN 'SU'
    WHEN 'Địa lý' THEN 'DIA'
    WHEN 'Giáo dục kinh tế và pháp luật' THEN 'GDKT_PL'
    ELSE ma_mon
END
WHERE ma_mon IS NULL
  AND to_regclass('public.diem_thi') IS NOT NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema='public' AND table_name='diem_thi' AND column_name='ma_mon'
    ) THEN
        ALTER TABLE public.diem_thi
            DROP CONSTRAINT IF EXISTS diem_thi_ma_mon_fkey;

        ALTER TABLE public.diem_thi
            ADD CONSTRAINT diem_thi_ma_mon_fkey
            FOREIGN KEY (ma_mon)
            REFERENCES public.mon_thi(ma_mon)
            ON DELETE RESTRICT;
    END IF;
END $$;

DROP INDEX IF EXISTS public.idx_diem_thi_unique;

CREATE UNIQUE INDEX IF NOT EXISTS idx_diem_thi_unique_mon
ON public.diem_thi(ma_thi_sinh, nam, ma_mon)
WHERE ma_mon IS NOT NULL;


-- =========================================================
-- 2) APPLICATION DOSSIER / WORKFLOW
-- One dossier per candidate per admission year.
-- =========================================================
CREATE TABLE IF NOT EXISTS public.ho_so_xet_tuyen (
    ma_ho_so BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_thi_sinh BIGINT NOT NULL
        REFERENCES public.thi_sinh(ma_thi_sinh)
        ON DELETE CASCADE,
    nam SMALLINT NOT NULL DEFAULT 2025,
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'nhap',
    ma_can_bo_phu_trach BIGINT
        REFERENCES public.can_bo(ma_can_bo)
        ON DELETE SET NULL,
    ngay_nop TIMESTAMP WITH TIME ZONE,
    ngay_duyet TIMESTAMP WITH TIME ZONE,
    ghi_chu TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT ho_so_trang_thai_check CHECK (
        trang_thai IN ('nhap','da_nop','dang_duyet','yeu_cau_bo_sung','hoan_tat')
    ),
    CONSTRAINT ho_so_thi_sinh_nam_unique UNIQUE (ma_thi_sinh, nam)
);

INSERT INTO public.ho_so_xet_tuyen(ma_thi_sinh, nam, trang_thai, ngay_nop)
SELECT DISTINCT
    nv.ma_thi_sinh,
    nv.nam,
    'da_nop',
    MIN(nv.created_at) OVER (PARTITION BY nv.ma_thi_sinh, nv.nam)
FROM public.nguyen_vong nv
ON CONFLICT (ma_thi_sinh, nam) DO NOTHING;

ALTER TABLE public.nguyen_vong
    ADD COLUMN IF NOT EXISTS ma_ho_so BIGINT;

UPDATE public.nguyen_vong nv
SET ma_ho_so = hs.ma_ho_so
FROM public.ho_so_xet_tuyen hs
WHERE hs.ma_thi_sinh = nv.ma_thi_sinh
  AND hs.nam = nv.nam
  AND nv.ma_ho_so IS NULL;

ALTER TABLE public.nguyen_vong
    DROP CONSTRAINT IF EXISTS nguyen_vong_ma_ho_so_fkey;

ALTER TABLE public.nguyen_vong
    ADD CONSTRAINT nguyen_vong_ma_ho_so_fkey
    FOREIGN KEY (ma_ho_so)
    REFERENCES public.ho_so_xet_tuyen(ma_ho_so)
    ON DELETE CASCADE;

DROP INDEX IF EXISTS public.idx_nguyen_vong_unique_order;

CREATE UNIQUE INDEX IF NOT EXISTS idx_nguyen_vong_ho_so_order
ON public.nguyen_vong(ma_ho_so, thu_tu_nguyen_vong)
WHERE ma_ho_so IS NOT NULL;


-- =========================================================
-- 3) FK INTEGRITY FOR METHODS / SCHOOLS / SUBJECT COMBINATIONS
-- =========================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='nguyen_vong_ma_phuong_thuc_fkey') THEN
        ALTER TABLE public.nguyen_vong
        ADD CONSTRAINT nguyen_vong_ma_phuong_thuc_fkey
        FOREIGN KEY (ma_phuong_thuc)
        REFERENCES public.phuong_thuc_xet_tuyen(ma_phuong_thuc)
        ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='dieu_kien_xet_tuyen_thang_ma_truong_fkey') THEN
        ALTER TABLE public.dieu_kien_xet_tuyen_thang
        ADD CONSTRAINT dieu_kien_xet_tuyen_thang_ma_truong_fkey
        FOREIGN KEY (ma_truong)
        REFERENCES public.truong_dh(ma_tuyen_sinh)
        ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='quy_doi_chung_chi_ma_truong_fkey') THEN
        ALTER TABLE public.quy_doi_chung_chi
        ADD CONSTRAINT quy_doi_chung_chi_ma_truong_fkey
        FOREIGN KEY (ma_truong)
        REFERENCES public.truong_dh(ma_tuyen_sinh)
        ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='dieu_kien_xet_tuyen_thang_ma_pt_fkey') THEN
        ALTER TABLE public.dieu_kien_xet_tuyen_thang
        ADD CONSTRAINT dieu_kien_xet_tuyen_thang_ma_pt_fkey
        FOREIGN KEY (ma_phuong_thuc)
        REFERENCES public.phuong_thuc_xet_tuyen(ma_phuong_thuc)
        ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='quy_doi_chung_chi_ma_pt_fkey') THEN
        ALTER TABLE public.quy_doi_chung_chi
        ADD CONSTRAINT quy_doi_chung_chi_ma_pt_fkey
        FOREIGN KEY (ma_phuong_thuc)
        REFERENCES public.phuong_thuc_xet_tuyen(ma_phuong_thuc)
        ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='nganh_to_hop_nganh_fkey') THEN
        ALTER TABLE public.nganh_to_hop_xet_tuyen
        ADD CONSTRAINT nganh_to_hop_nganh_fkey
        FOREIGN KEY (ma_nganh)
        REFERENCES public.nganh(ma_nganh)
        ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='nganh_to_hop_ma_to_hop_fkey') THEN
        ALTER TABLE public.nganh_to_hop_xet_tuyen
        ADD CONSTRAINT nganh_to_hop_ma_to_hop_fkey
        FOREIGN KEY (ma_to_hop)
        REFERENCES public.to_hop_xet_tuyen(ma_to_hop)
        ON DELETE CASCADE;
    END IF;
END $$;


-- =========================================================
-- 4) FLOOR SCORE BELONGS TO ADMISSION DATA, NOT TUITION
-- Safe to rerun whether the old hoc_phi.diem_san_* columns still exist or not.
-- =========================================================
CREATE TABLE IF NOT EXISTS public.nguong_dau_vao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_truong VARCHAR(20) NOT NULL
        REFERENCES public.truong_dh(ma_tuyen_sinh)
        ON DELETE CASCADE,
    nam SMALLINT NOT NULL DEFAULT 2025,
    ma_nganh VARCHAR(20)
        REFERENCES public.nganh(ma_nganh)
        ON DELETE CASCADE,
    ma_phuong_thuc VARCHAR(20)
        REFERENCES public.phuong_thuc_xet_tuyen(ma_phuong_thuc)
        ON DELETE SET NULL,
    diem_san_min NUMERIC(6,2),
    diem_san_max NUMERIC(6,2),
    trang_thai VARCHAR(30) DEFAULT 'chua_xac_minh',
    ghi_chu TEXT,
    source_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT nguong_dau_vao_range_check
        CHECK (
            diem_san_min IS NULL OR diem_san_max IS NULL
            OR diem_san_max >= diem_san_min
        )
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'hoc_phi'
          AND column_name = 'diem_san_min'
    ) THEN
        -- Use dynamic SQL because these legacy columns may already be gone.
        EXECUTE $sql$
            INSERT INTO public.nguong_dau_vao(
                ma_truong, nam, diem_san_min, diem_san_max,
                trang_thai, ghi_chu, source_url
            )
            SELECT
                ma_truong,
                nam,
                diem_san_min,
                diem_san_max,
                COALESCE(diem_san_trang_thai, 'chua_xac_minh'),
                diem_san_ghi_chu,
                diem_san_source_url
            FROM public.hoc_phi
            WHERE diem_san_min IS NOT NULL
               OR diem_san_max IS NOT NULL
               OR diem_san_ghi_chu IS NOT NULL
               OR diem_san_source_url IS NOT NULL
        $sql$;

        -- Views depend on the old columns, so remove them before dropping columns.
        DROP VIEW IF EXISTS public.v_catalog_tuyen_sinh_2025;
        DROP VIEW IF EXISTS public.v_truong_tuyen_sinh_2025;

        EXECUTE $sql$
            ALTER TABLE public.hoc_phi
                DROP COLUMN IF EXISTS diem_san_min,
                DROP COLUMN IF EXISTS diem_san_max,
                DROP COLUMN IF EXISTS diem_san_trang_thai,
                DROP COLUMN IF EXISTS diem_san_ghi_chu,
                DROP COLUMN IF EXISTS diem_san_source_url
        $sql$;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_nguong_dau_vao_school_level
ON public.nguong_dau_vao(
    ma_truong,
    nam,
    COALESCE(ma_nganh,''),
    COALESCE(ma_phuong_thuc,'')
);

-- Recreate the public school/catalog views against nguong_dau_vao.
CREATE OR REPLACE VIEW public.v_truong_tuyen_sinh_2025 AS
SELECT
    t.ma_truong AS id_truong,
    t.ma_tuyen_sinh,
    t.ten_truong,

    h.hoc_phi_min,
    h.hoc_phi_max,
    h.don_vi AS hoc_phi_don_vi,
    h.trang_thai AS hoc_phi_trang_thai,
    h.source_url AS hoc_phi_source_url,

    c.chi_tieu,
    c.chi_tieu_min,
    c.chi_tieu_max,
    c.trang_thai AS chi_tieu_trang_thai,
    c.source_url AS chi_tieu_source_url,

    n.diem_san_min,
    n.diem_san_max,
    n.trang_thai AS diem_san_trang_thai,
    n.ghi_chu AS diem_san_ghi_chu,
    n.source_url AS diem_san_source_url

FROM public.truong_dh t
LEFT JOIN public.hoc_phi h
    ON h.ma_truong = t.ma_tuyen_sinh
   AND h.nam = 2025
LEFT JOIN public.chi_tieu_tuyen_sinh c
    ON c.ma_truong = t.ma_tuyen_sinh
   AND c.nam = 2025
   AND COALESCE(c.cap_do, 'truong') = 'truong'
LEFT JOIN public.nguong_dau_vao n
    ON n.ma_truong = t.ma_tuyen_sinh
   AND n.nam = 2025
   AND n.ma_nganh IS NULL
   AND n.ma_phuong_thuc IS NULL;

CREATE OR REPLACE VIEW public.v_catalog_tuyen_sinh_2025 AS
SELECT
    n.ma_nganh,
    n.ma_truong,
    n.ten_truong,
    n.ma_nganh_tuyen_sinh,
    n.ten_nganh,
    n.ma_nganh_bo,
    n.ten_nganh_bo,

    h.hoc_phi_min,
    h.hoc_phi_max,
    h.hoc_phi_don_vi,
    h.hoc_phi_trang_thai,

    h.chi_tieu,
    h.chi_tieu_min,
    h.chi_tieu_max,
    h.chi_tieu_trang_thai,

    h.diem_san_min,
    h.diem_san_max,
    h.diem_san_trang_thai,
    h.diem_san_ghi_chu,
    h.diem_san_source_url

FROM public.v_nganh_2025 n
LEFT JOIN public.v_truong_tuyen_sinh_2025 h
    ON h.ma_tuyen_sinh = n.ma_truong;


-- =========================================================
-- 5) RESULT NORMALIZATION
-- ma_nv already identifies the candidate through nguyen_vong -> ho_so.
-- Keep old ma_thi_sinh for compatibility for now, but prevent mismatch.
-- =========================================================
CREATE OR REPLACE FUNCTION public.check_ket_qua_candidate_consistency()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_ma_thi_sinh BIGINT;
BEGIN
    SELECT hs.ma_thi_sinh
      INTO v_ma_thi_sinh
    FROM public.nguyen_vong nv
    LEFT JOIN public.ho_so_xet_tuyen hs ON hs.ma_ho_so = nv.ma_ho_so
    WHERE nv.ma_nv = NEW.ma_nv;

    IF v_ma_thi_sinh IS NOT NULL
       AND NEW.ma_thi_sinh IS DISTINCT FROM v_ma_thi_sinh THEN
        RAISE EXCEPTION 'ket_qua_xet_tuyen.ma_thi_sinh does not match nguyen_vong/ho_so';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_check_ket_qua_candidate
ON public.ket_qua_xet_tuyen;

CREATE TRIGGER trg_check_ket_qua_candidate
BEFORE INSERT OR UPDATE
ON public.ket_qua_xet_tuyen
FOR EACH ROW
EXECUTE FUNCTION public.check_ket_qua_candidate_consistency();


-- =========================================================
-- 6) RLS / VIEW SECURITY
-- =========================================================
ALTER TABLE public.mon_thi ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS public_read ON public.mon_thi;
CREATE POLICY public_read ON public.mon_thi
FOR SELECT TO anon, authenticated USING (true);
GRANT SELECT ON public.mon_thi TO anon, authenticated;

ALTER TABLE public.nguong_dau_vao ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS public_read ON public.nguong_dau_vao;
CREATE POLICY public_read ON public.nguong_dau_vao
FOR SELECT TO anon, authenticated USING (true);
GRANT SELECT ON public.nguong_dau_vao TO anon, authenticated;

ALTER TABLE public.ho_so_xet_tuyen ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ho_so_xet_tuyen FROM anon, authenticated;

ALTER VIEW public.v_catalog_tuyen_sinh_2025 SET (security_invoker = true);
ALTER VIEW public.v_truong_tuyen_sinh_2025 SET (security_invoker = true);
ALTER VIEW public.v_diem_chuan_2025 SET (security_invoker = true);
ALTER VIEW public.v_nganh_2025 SET (security_invoker = true);
ALTER VIEW public.v_nganh_to_hop_2025 SET (security_invoker = true);
ALTER VIEW public.v_phuong_thuc_xet_tuyen_2025 SET (security_invoker = true);
ALTER VIEW public.v_chung_chi_quy_doi SET (security_invoker = true);
ALTER VIEW public.v_xet_tuyen_thang_kha_dung SET (security_invoker = true);

COMMIT;


-- =========================================================
-- QA
-- =========================================================
SELECT
    to_regclass('public.mon_thi') AS mon_thi,
    to_regclass('public.ho_so_xet_tuyen') AS ho_so_xet_tuyen,
    to_regclass('public.nguong_dau_vao') AS nguong_dau_vao;

SELECT COUNT(*) AS nguyen_vong_chua_co_ho_so
FROM public.nguyen_vong
WHERE ma_ho_so IS NULL;

SELECT COUNT(*) AS diem_thi_chua_map_mon
FROM public.diem_thi
WHERE ma_mon IS NULL;
