-- UniAdmSys: ALL-IN-ONE học phí 2025-2026
-- Tạo đủ 1 dòng cho TẤT CẢ trường trong truong_dh.
-- 131 trường/cơ sở đã có mức học phí xác minh; trường còn lại giữ NULL, không bịa.
-- Có thể chạy lại an toàn.

BEGIN;

CREATE TABLE IF NOT EXISTS public.hoc_phi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

ALTER TABLE public.hoc_phi
    ADD COLUMN IF NOT EXISTS ma_truong VARCHAR(20),
    ADD COLUMN IF NOT EXISTS nam INTEGER,
    ADD COLUMN IF NOT EXISTS nam_hoc VARCHAR(20),
    ADD COLUMN IF NOT EXISTS hoc_phi_min BIGINT,
    ADD COLUMN IF NOT EXISTS hoc_phi_max BIGINT,
    ADD COLUMN IF NOT EXISTS don_vi VARCHAR(30) DEFAULT 'VND/năm',
    ADD COLUMN IF NOT EXISTS trang_thai VARCHAR(30) DEFAULT 'chua_xac_minh',
    ADD COLUMN IF NOT EXISTS ghi_chu TEXT,
    ADD COLUMN IF NOT EXISTS source_type VARCHAR(30),
    ADD COLUMN IF NOT EXISTS source_url TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now();

DELETE FROM public.hoc_phi
WHERE nam = 2025;

-- Seed toàn bộ trường hiện có trong DB.
INSERT INTO public.hoc_phi (
    ma_truong, nam, nam_hoc, don_vi, trang_thai, ghi_chu
)
SELECT DISTINCT
    trim(t.ma_tuyen_sinh),
    2025,
    '2025-2026',
    'VND/năm',
    'chua_xac_minh',
    'Chưa có mức học phí 2025-2026 được xác minh trong bộ nguồn hiện tại'
FROM public.truong_dh t
WHERE NULLIF(trim(t.ma_tuyen_sinh),'') IS NOT NULL;

-- Fill 131 trường/cơ sở đã có dữ liệu.
WITH verified (
    ma_truong, hoc_phi_min, hoc_phi_max, don_vi, ghi_chu, source_url
) AS (
    VALUES
('QHI',34000000,40000000,'VND/năm','34 - 40 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHS',14100000,14100000,'VND/năm','14,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHT',16900000,38000000,'VND/năm','16,9 - 38 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHX',16900000,33000000,'VND/năm','16,9 - 33 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHE',31500000,46000000,'VND/năm','31,5 - 46 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHL',27000000,31800000,'VND/năm','27 - 31,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHF',16900000,65000000,'VND/năm','16,9 - 65 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('VJU',25000000,58000000,'VND/năm','25 - 58 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHY',62000000,62000000,'VND/năm','62 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHK',30400000,33800000,'VND/năm','30,4 - 33,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHD',40000000,130000000,'VND/năm','40 - 130 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHQ',39750000,50600000,'VND/năm','39,75 - 50,6 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QSA',23850000,27750000,'VND/năm','23,85 - 27,75 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QSB',30000000,84000000,'VND/năm','30 triệu (chương trình chuẩn, tài năng, Việt - Pháp); 84 triệu (đào tạo bằng tiếng Anh, tiên tiến); 60 triệu (định hướng Nhật Bản)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QSC',37000000,55000000,'VND/năm','37 triệu (chương trình chuẩn); 55 triệu (chương trình tiên tiến)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QST',28400000,55400000,'VND/năm','28,4 - 55,4 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QSX',16600000,29800000,'VND/năm','16,6 - 29,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QSK',31500000,65000000,'VND/năm','31,5 triệu (chương trình chuẩn); 65 triệu (chương trình bằng Tiếng Anh)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QSQ',50000000,60000000,'VND/năm','50 - 60 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('BKA',28000000,90000000,'VND/năm','28 - 35 triệu (chương trình chuẩn); 35 - 45 triệu (giảng dạy bằng tiếng Anh/tiên tiến); 39 - 45 triệu (tăng cường ngoại ngữ); 39 - 42 triệu (PFIEV); 78 - 90 triệu (liên kết)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TCT',22000000,40000000,'VND/năm','22 - 25,9 triệu (chương trình chuẩn); 37 - 40 triệu (tiên tiến/chất lượng cao)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('LDA',20850000,30000000,'VND/năm','20,85 triệu (chương trình chuẩn); 30 triệu (định hướng chuyên sâu nghề nghiệp quốc tế)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('MIT',25000000,25000000,'VND/năm','25 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDN',22000000,96000000,'VND/năm','22 - 96 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('YDD',18090000,19300000,'VND/năm','18,09 - 19,3 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDU',18500000,36750000,'VND/năm','18,5 - 36,75 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DKH',17100000,27600000,'VND/năm','17,1 - 27,6 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('NHF',29250000,49500000,'VND/năm','29,25 - 49,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('ETU',29500000,61000000,'VND/năm','29,5 - 61 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHT',15100000,17400000,'VND/năm','15,1 - 17,4 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('KCN',56000000,125000000,'VND/năm','56 - 125 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DQK',12780000,83200000,'VND/năm','12,78 - 83,2 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHK',18800000,34000000,'VND/năm','18,8 - 24,5 triệu (chương trình chuẩn); 34 triệu (đào tạo bằng tiếng Anh)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('KHA',18000000,25000000,'VND/năm','18 - 25 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('KSA',33800000,39900000,'VND/năm','33,8 - 39,9 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DKY',26600000,43540000,'VND/năm','26,6 - 43,54 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('LNH',15000000,19000000,'VND/năm','15 - 19 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHA',16000000,16000000,'VND/năm','16 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('LPH',29250000,58510000,'VND/năm','29,25 - 58,51 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('LPS',39750000,47170000,'VND/năm','39,75 - 47,17 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('MHN',21500000,22900000,'VND/năm','21,5 - 22,9 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('MBS',24000000,49500000,'VND/năm','24 - 28,5 triệu (chương trình chuẩn); 46,5 - 49,5 triệu (chất lượng cao)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('NHS',23210000,39750000,'VND/năm','23,21 triệu (chương trình chuẩn); 39,75 triệu (chất lượng cao)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHF',15900000,21800000,'VND/năm','15,9 - 21,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('NTH',25500000,75000000,'VND/năm','25,5 - 27,5 triệu (chương trình chuẩn); 31,5 - 65 triệu (định hướng nghề nghiệp); 49 - 51 triệu (chất lượng cao); 73 - 75 triệu (tiên tiến)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('NTT',25000000,39600000,'VND/năm','25 - 39 triệu (chương trình chuẩn); 37,2 triệu (cử nhân quốc tế); 39,6 triệu (chuẩn quốc tế NIIE)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('PKA',26500000,128000000,'VND/năm','26,5 - 128 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DPD',23000000,26000000,'VND/năm','23 - 26 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DBH',18000000,20000000,'VND/năm','18 - 20 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HIU',44000000,144000000,'VND/năm','44 - 144 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DQN',18750000,22670000,'VND/năm','18,75 - 22 triệu (hệ cử nhân); 22,67 triệu (hệ kĩ sư)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('SGD',18480000,37600000,'VND/năm','18,48 - 37,6 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('SP2',15900000,18500000,'VND/năm','15,9 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHS',15900000,18500000,'VND/năm','15,9 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DMS',30000000,64000000,'VND/năm','30 - 64 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TQU',9800000,14300000,'VND/năm','9,8 - 14,3 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DTL',33600000,46900000,'VND/năm','33,6 - 46,9 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TDD',25340000,37500000,'VND/năm','25,34 - 36,89 triệu (chương trình chuẩn); 37,5 triệu (CNTT CodeGym)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HNM',15900000,18500000,'VND/năm','15,9 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TMU',24000000,38500000,'VND/năm','24 - 27,9 triệu (chương trình chuẩn); 38,5 triệu (định hướng nghề nghiệp)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DTT',29770000,84000000,'VND/năm','29,77 - 66,79 triệu (chuẩn); 53 - 64 triệu (tiên tiến); 78 - 84 triệu (tiếng Anh); 75 - 83 triệu (liên kết quốc tế)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DVT',15000000,50000000,'VND/năm','15 - 50 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('VHH',13800000,13800000,'VND/năm','13,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TDV',11900000,16300000,'VND/năm','11,9 - 16,3 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('XDA',18500000,37000000,'VND/năm','18,5 triệu (chương trình chuẩn); 37 triệu (liên kết)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('MTU',14000000,14800000,'VND/năm','14 - 14,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('XDT',15900000,18500000,'VND/năm','15,9 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('YCT',44400000,63100000,'VND/năm','44,4 - 63,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHY',36600000,61100000,'VND/năm','36,6 - 61,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('YPB',45000000,58000000,'VND/năm','45 - 58 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('YTB',42000000,55500000,'VND/năm','42 - 55,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('YDS',30000000,84700000,'VND/năm','30 - 84,7 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('YHB',16900000,62200000,'VND/năm','16,9 - 62,2 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TYS',41800000,55200000,'VND/năm','41,8 - 55,2 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('YTC',18590000,34220000,'VND/năm','18,59 - 34,22 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('GDU',20700000,170000000,'VND/năm','20,7 - 170 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HBT',18500000,33800000,'VND/năm','18,5 - 33,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('BVH',29600000,62500000,'VND/năm','29,6 - 37,6 triệu (chuẩn); 49,2 - 55 triệu (chất lượng cao); 54 - 62,5 triệu (liên kết/định hướng ứng dụng)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('KMA',19250000,19250000,'VND/năm','19,25 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('NHH',27000000,40000000,'VND/năm','27 - 28 triệu (chuẩn); 40 triệu (chất lượng cao)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HQT',34000000,45000000,'VND/năm','34 - 45 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HPN',14970000,19100000,'VND/năm','14,97 - 19,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HVQ',15900000,18500000,'VND/năm','15,9 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HTC',20000000,55000000,'VND/năm','20 - 28 triệu (chuẩn); 50 - 55 triệu (định hướng chứng chỉ quốc tế)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHD',13800000,13800000,'VND/năm','13,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QSY',53200000,70000000,'VND/năm','53,2 - 70 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('UEF',80000000,80000000,'VND/năm','80 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHQ',17000000,18500000,'VND/năm','17 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('SPK',32500000,62000000,'VND/năm','32,5 - 62 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HCP',20150000,28300000,'VND/năm','20,15 triệu (chuẩn); 28,3 triệu (chất lượng cao)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HYD',27600000,31100000,'VND/năm','27,6 - 31,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('VHD',15900000,18500000,'VND/năm','15,9 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DQU',20600000,24000000,'VND/năm','20,6 - 24 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DCL',13200000,78000000,'VND/năm','13,2 - 78 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDA',23000000,35000000,'VND/năm','23 - 35 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('VLU',20140000,23370000,'VND/năm','20,14 - 23,37 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DAD',17600000,85990000,'VND/năm','17,6 - 85,99 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('SKH',15500000,24000000,'VND/năm','15,5 - 17,9 triệu (chuẩn); 24 triệu (bằng tiếng Anh)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DLH',35000000,49000000,'VND/năm','35 - 49 triệu (chuẩn); 40 - 42 triệu (Việt - Nhật); 40 - 42 triệu (Việt - Hoa)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DCQ',25150000,27370000,'VND/năm','25,15 - 27,37 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DPX',20630000,25940000,'VND/năm','20,63 - 25,94 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DNC',20000000,80000000,'VND/năm','20 - 80 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('GTA',20000000,30000000,'VND/năm','20 triệu (chuẩn); 30 triệu (tăng cường tiếng Anh/đào tạo đặt hàng/định hướng Nhật Bản)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('VTT',10500000,61500000,'VND/năm','10,5 - 61,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TDL',15000000,24000000,'VND/năm','15 - 24 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('KTA',15200000,18500000,'VND/năm','15,2 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DQT',15600000,17000000,'VND/năm','15,6 - 17 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DVH',17470000,44100000,'VND/năm','17,47 - 44,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('SDU',18000000,20000000,'VND/năm','18 - 20 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('CMC',21550000,23650000,'VND/năm','21,55 - 23,65 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TDM',22800000,34690000,'VND/năm','22,8 - 34,69 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('KTD',27840000,37800000,'VND/năm','27,84 - 37,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHV',33000000,33000000,'VND/năm','33 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('SIU',34300000,72000000,'VND/năm','34,3 - 72 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DNT',38130000,39360000,'VND/năm','38,13 - 39,36 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('VGU',42600000,45400000,'VND/năm','42,6 - 45,4 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('UKH',10400000,15170000,'VND/năm','10,4 - 15,17 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDK',25900000,36200000,'VND/năm','25,9 - 30,896 triệu (chuẩn); 26,3 triệu (PFIEV); 36,2 triệu (tiên tiến)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('VKU',16000000,18000000,'VND/năm','16 - 18 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDQ',27500000,40000000,'VND/năm','27,5 - 40 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDF',16900000,19500000,'VND/năm','16,9 - 19,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDS',14820000,17240000,'VND/năm','14,82 - 17,24 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DSK',15900000,25900000,'VND/năm','15,9 - 25,9 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDP',15000000,17500000,'VND/năm','15 - 17,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDY',16900000,31100000,'VND/năm','16,9 - 31,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDV',31800000,48100000,'VND/năm','31,8 - 48,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DTC',16500000,16500000,'VND/năm','16,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DTE',16000000,57650000,'VND/năm','16 - 18 triệu (chuẩn); 56,78 - 57,65 triệu (bằng tiếng Anh)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DTN',14100000,28900000,'VND/năm','14,1 - 16,4 triệu (chuẩn); 28,9 triệu (tiên tiến)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DTS',15900000,15900000,'VND/năm','15,9 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DTY',43000000,59000000,'VND/năm','43 - 59 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html')
)
UPDATE public.hoc_phi h
SET
    hoc_phi_min = v.hoc_phi_min,
    hoc_phi_max = v.hoc_phi_max,
    don_vi = v.don_vi,
    ghi_chu = v.ghi_chu,
    source_type = 'aggregator',
    source_url = v.source_url,
    trang_thai = 'da_xac_minh'
FROM verified v
WHERE h.nam = 2025
  AND h.ma_truong = v.ma_truong;

CREATE INDEX IF NOT EXISTS idx_hoc_phi_truong_nam
ON public.hoc_phi(ma_truong, nam);

CREATE INDEX IF NOT EXISTS idx_hoc_phi_status
ON public.hoc_phi(nam, trang_thai);

CREATE INDEX IF NOT EXISTS idx_hoc_phi_minmax
ON public.hoc_phi(hoc_phi_min, hoc_phi_max);

COMMIT;

-- QA tổng
SELECT
    (SELECT COUNT(DISTINCT ma_tuyen_sinh)
       FROM public.truong_dh
      WHERE NULLIF(trim(ma_tuyen_sinh),'') IS NOT NULL) AS tong_truong_trong_db,
    COUNT(*) AS so_dong_hoc_phi_2025,
    COUNT(*) FILTER (WHERE trang_thai = 'da_xac_minh') AS da_xac_minh,
    COUNT(*) FILTER (WHERE trang_thai = 'chua_xac_minh') AS chua_xac_minh,
    ROUND(
        100.0 * COUNT(*) FILTER (WHERE trang_thai = 'da_xac_minh')
        / NULLIF(COUNT(*),0),
        2
    ) AS coverage_percent
FROM public.hoc_phi
WHERE nam = 2025;

-- Duplicate check: phải ra 0 rows.
SELECT ma_truong, nam, COUNT(*) AS so_dong
FROM public.hoc_phi
WHERE nam = 2025
GROUP BY ma_truong, nam
HAVING COUNT(*) > 1;

-- Danh sách chưa xác minh.
SELECT
    h.ma_truong,
    t.ten_truong,
    h.trang_thai
FROM public.hoc_phi h
LEFT JOIN public.truong_dh t
  ON t.ma_tuyen_sinh = h.ma_truong
WHERE h.nam = 2025
  AND h.trang_thai = 'chua_xac_minh'
ORDER BY t.ten_truong NULLS LAST, h.ma_truong;
