-- UniAdmSys: ALL-IN-ONE học phí 2025-2026
-- Nguồn tổng hợp công khai: Báo Lâm Đồng, 19/08/2025
-- 131 cơ sở đào tạo. Mức min/max là mức thấp nhất/cao nhất trong mô tả công bố.

CREATE TABLE IF NOT EXISTS public.hoc_phi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_truong VARCHAR(20) NOT NULL,
    nam INTEGER NOT NULL,
    nam_hoc VARCHAR(20) NOT NULL,
    hoc_phi_min BIGINT,
    hoc_phi_max BIGINT,
    don_vi VARCHAR(30) NOT NULL DEFAULT 'VND/năm',
    ghi_chu TEXT,
    source_url TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    CONSTRAINT hoc_phi_min_nonnegative CHECK (hoc_phi_min IS NULL OR hoc_phi_min >= 0),
    CONSTRAINT hoc_phi_max_nonnegative CHECK (hoc_phi_max IS NULL OR hoc_phi_max >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_hoc_phi_truong_nam
ON public.hoc_phi(ma_truong, nam);

CREATE INDEX IF NOT EXISTS idx_hoc_phi_minmax
ON public.hoc_phi(hoc_phi_min, hoc_phi_max);

INSERT INTO public.hoc_phi (
    ma_truong, nam, nam_hoc, hoc_phi_min, hoc_phi_max, don_vi, ghi_chu, source_url
)
VALUES
('QHI',2025,'2025-2026',34000000,40000000,'VND/năm','34 - 40 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHS',2025,'2025-2026',14100000,14100000,'VND/năm','14,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHT',2025,'2025-2026',16900000,38000000,'VND/năm','16,9 - 38 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHX',2025,'2025-2026',16900000,33000000,'VND/năm','16,9 - 33 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHE',2025,'2025-2026',31500000,46000000,'VND/năm','31,5 - 46 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHL',2025,'2025-2026',27000000,31800000,'VND/năm','27 - 31,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHF',2025,'2025-2026',16900000,65000000,'VND/năm','16,9 - 65 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('VJU',2025,'2025-2026',25000000,58000000,'VND/năm','25 - 58 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHY',2025,'2025-2026',62000000,62000000,'VND/năm','62 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHK',2025,'2025-2026',30400000,33800000,'VND/năm','30,4 - 33,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHD',2025,'2025-2026',40000000,130000000,'VND/năm','40 - 130 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QHQ',2025,'2025-2026',39750000,50600000,'VND/năm','39,75 - 50,6 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QSA',2025,'2025-2026',23850000,27750000,'VND/năm','23,85 - 27,75 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QSB',2025,'2025-2026',30000000,84000000,'VND/năm','30 triệu (chương trình chuẩn, tài năng, Việt - Pháp); 84 triệu (đào tạo bằng tiếng Anh, tiên tiến); 60 triệu (định hướng Nhật Bản)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QSC',2025,'2025-2026',37000000,55000000,'VND/năm','37 triệu (chương trình chuẩn); 55 triệu (chương trình tiên tiến)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QST',2025,'2025-2026',28400000,55400000,'VND/năm','28,4 - 55,4 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QSX',2025,'2025-2026',16600000,29800000,'VND/năm','16,6 - 29,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QSK',2025,'2025-2026',31500000,65000000,'VND/năm','31,5 triệu (chương trình chuẩn); 65 triệu (chương trình bằng Tiếng Anh)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QSQ',2025,'2025-2026',50000000,60000000,'VND/năm','50 - 60 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('BKA',2025,'2025-2026',28000000,90000000,'VND/năm','28 - 35 triệu (chương trình chuẩn); 35 - 45 triệu (giảng dạy bằng tiếng Anh/tiên tiến); 39 - 45 triệu (tăng cường ngoại ngữ); 39 - 42 triệu (PFIEV); 78 - 90 triệu (liên kết)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TCT',2025,'2025-2026',22000000,40000000,'VND/năm','22 - 25,9 triệu (chương trình chuẩn); 37 - 40 triệu (tiên tiến/chất lượng cao)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('LDA',2025,'2025-2026',20850000,30000000,'VND/năm','20,85 triệu (chương trình chuẩn); 30 triệu (định hướng chuyên sâu nghề nghiệp quốc tế)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('MIT',2025,'2025-2026',25000000,25000000,'VND/năm','25 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDN',2025,'2025-2026',22000000,96000000,'VND/năm','22 - 96 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('YDD',2025,'2025-2026',18090000,19300000,'VND/năm','18,09 - 19,3 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDU',2025,'2025-2026',18500000,36750000,'VND/năm','18,5 - 36,75 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DKH',2025,'2025-2026',17100000,27600000,'VND/năm','17,1 - 27,6 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('NHF',2025,'2025-2026',29250000,49500000,'VND/năm','29,25 - 49,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('ETU',2025,'2025-2026',29500000,61000000,'VND/năm','29,5 - 61 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHT',2025,'2025-2026',15100000,17400000,'VND/năm','15,1 - 17,4 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('KCN',2025,'2025-2026',56000000,125000000,'VND/năm','56 - 125 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DQK',2025,'2025-2026',12780000,83200000,'VND/năm','12,78 - 83,2 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHK',2025,'2025-2026',18800000,34000000,'VND/năm','18,8 - 24,5 triệu (chương trình chuẩn); 34 triệu (đào tạo bằng tiếng Anh)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('KHA',2025,'2025-2026',18000000,25000000,'VND/năm','18 - 25 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('KSA',2025,'2025-2026',33800000,39900000,'VND/năm','33,8 - 39,9 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DKY',2025,'2025-2026',26600000,43540000,'VND/năm','26,6 - 43,54 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('LNH',2025,'2025-2026',15000000,19000000,'VND/năm','15 - 19 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHA',2025,'2025-2026',16000000,16000000,'VND/năm','16 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('LPH',2025,'2025-2026',29250000,58510000,'VND/năm','29,25 - 58,51 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('LPS',2025,'2025-2026',39750000,47170000,'VND/năm','39,75 - 47,17 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('MHN',2025,'2025-2026',21500000,22900000,'VND/năm','21,5 - 22,9 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('MBS',2025,'2025-2026',24000000,49500000,'VND/năm','24 - 28,5 triệu (chương trình chuẩn); 46,5 - 49,5 triệu (chất lượng cao)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('NHS',2025,'2025-2026',23210000,39750000,'VND/năm','23,21 triệu (chương trình chuẩn); 39,75 triệu (chất lượng cao)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHF',2025,'2025-2026',15900000,21800000,'VND/năm','15,9 - 21,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('NTH',2025,'2025-2026',25500000,75000000,'VND/năm','25,5 - 27,5 triệu (chương trình chuẩn); 31,5 - 65 triệu (định hướng nghề nghiệp); 49 - 51 triệu (chất lượng cao); 73 - 75 triệu (tiên tiến)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('NTT',2025,'2025-2026',25000000,39600000,'VND/năm','25 - 39 triệu (chương trình chuẩn); 37,2 triệu (cử nhân quốc tế); 39,6 triệu (chuẩn quốc tế NIIE)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('PKA',2025,'2025-2026',26500000,128000000,'VND/năm','26,5 - 128 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DPD',2025,'2025-2026',23000000,26000000,'VND/năm','23 - 26 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DBH',2025,'2025-2026',18000000,20000000,'VND/năm','18 - 20 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HIU',2025,'2025-2026',44000000,144000000,'VND/năm','44 - 144 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DQN',2025,'2025-2026',18750000,22670000,'VND/năm','18,75 - 22 triệu (hệ cử nhân); 22,67 triệu (hệ kĩ sư)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('SGD',2025,'2025-2026',18480000,37600000,'VND/năm','18,48 - 37,6 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('SP2',2025,'2025-2026',15900000,18500000,'VND/năm','15,9 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHS',2025,'2025-2026',15900000,18500000,'VND/năm','15,9 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DMS',2025,'2025-2026',30000000,64000000,'VND/năm','30 - 64 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TQU',2025,'2025-2026',9800000,14300000,'VND/năm','9,8 - 14,3 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DTL',2025,'2025-2026',33600000,46900000,'VND/năm','33,6 - 46,9 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TDD',2025,'2025-2026',25340000,37500000,'VND/năm','25,34 - 36,89 triệu (chương trình chuẩn); 37,5 triệu (CNTT CodeGym)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HNM',2025,'2025-2026',15900000,18500000,'VND/năm','15,9 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TMU',2025,'2025-2026',24000000,38500000,'VND/năm','24 - 27,9 triệu (chương trình chuẩn); 38,5 triệu (định hướng nghề nghiệp)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DTT',2025,'2025-2026',29770000,84000000,'VND/năm','29,77 - 66,79 triệu (chuẩn); 53 - 64 triệu (tiên tiến); 78 - 84 triệu (tiếng Anh); 75 - 83 triệu (liên kết quốc tế)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DVT',2025,'2025-2026',15000000,50000000,'VND/năm','15 - 50 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('VHH',2025,'2025-2026',13800000,13800000,'VND/năm','13,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TDV',2025,'2025-2026',11900000,16300000,'VND/năm','11,9 - 16,3 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('XDA',2025,'2025-2026',18500000,37000000,'VND/năm','18,5 triệu (chương trình chuẩn); 37 triệu (liên kết)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('MTU',2025,'2025-2026',14000000,14800000,'VND/năm','14 - 14,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('XDT',2025,'2025-2026',15900000,18500000,'VND/năm','15,9 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('YCT',2025,'2025-2026',44400000,63100000,'VND/năm','44,4 - 63,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHY',2025,'2025-2026',36600000,61100000,'VND/năm','36,6 - 61,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('YPB',2025,'2025-2026',45000000,58000000,'VND/năm','45 - 58 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('YTB',2025,'2025-2026',42000000,55500000,'VND/năm','42 - 55,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('YDS',2025,'2025-2026',30000000,84700000,'VND/năm','30 - 84,7 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('YHB',2025,'2025-2026',16900000,62200000,'VND/năm','16,9 - 62,2 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TYS',2025,'2025-2026',41800000,55200000,'VND/năm','41,8 - 55,2 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('YTC',2025,'2025-2026',18590000,34220000,'VND/năm','18,59 - 34,22 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('GDU',2025,'2025-2026',20700000,170000000,'VND/năm','20,7 - 170 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HBT',2025,'2025-2026',18500000,33800000,'VND/năm','18,5 - 33,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('BVH',2025,'2025-2026',29600000,62500000,'VND/năm','29,6 - 37,6 triệu (chuẩn); 49,2 - 55 triệu (chất lượng cao); 54 - 62,5 triệu (liên kết/định hướng ứng dụng)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('KMA',2025,'2025-2026',19250000,19250000,'VND/năm','19,25 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('NHH',2025,'2025-2026',27000000,40000000,'VND/năm','27 - 28 triệu (chuẩn); 40 triệu (chất lượng cao)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HQT',2025,'2025-2026',34000000,45000000,'VND/năm','34 - 45 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HPN',2025,'2025-2026',14970000,19100000,'VND/năm','14,97 - 19,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HVQ',2025,'2025-2026',15900000,18500000,'VND/năm','15,9 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HTC',2025,'2025-2026',20000000,55000000,'VND/năm','20 - 28 triệu (chuẩn); 50 - 55 triệu (định hướng chứng chỉ quốc tế)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHD',2025,'2025-2026',13800000,13800000,'VND/năm','13,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('QSY',2025,'2025-2026',53200000,70000000,'VND/năm','53,2 - 70 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('UEF',2025,'2025-2026',80000000,80000000,'VND/năm','80 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHQ',2025,'2025-2026',17000000,18500000,'VND/năm','17 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('SPK',2025,'2025-2026',32500000,62000000,'VND/năm','32,5 - 62 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HCP',2025,'2025-2026',20150000,28300000,'VND/năm','20,15 triệu (chuẩn); 28,3 triệu (chất lượng cao)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('HYD',2025,'2025-2026',27600000,31100000,'VND/năm','27,6 - 31,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('VHD',2025,'2025-2026',15900000,18500000,'VND/năm','15,9 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DQU',2025,'2025-2026',20600000,24000000,'VND/năm','20,6 - 24 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DCL',2025,'2025-2026',13200000,78000000,'VND/năm','13,2 - 78 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDA',2025,'2025-2026',23000000,35000000,'VND/năm','23 - 35 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('VLU',2025,'2025-2026',20140000,23370000,'VND/năm','20,14 - 23,37 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DAD',2025,'2025-2026',17600000,85990000,'VND/năm','17,6 - 85,99 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('SKH',2025,'2025-2026',15500000,24000000,'VND/năm','15,5 - 17,9 triệu (chuẩn); 24 triệu (bằng tiếng Anh)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DLH',2025,'2025-2026',35000000,49000000,'VND/năm','35 - 49 triệu (chuẩn); 40 - 42 triệu (Việt - Nhật); 40 - 42 triệu (Việt - Hoa)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DCQ',2025,'2025-2026',25150000,27370000,'VND/năm','25,15 - 27,37 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DPX',2025,'2025-2026',20630000,25940000,'VND/năm','20,63 - 25,94 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DNC',2025,'2025-2026',20000000,80000000,'VND/năm','20 - 80 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('GTA',2025,'2025-2026',20000000,30000000,'VND/năm','20 triệu (chuẩn); 30 triệu (tăng cường tiếng Anh/đào tạo đặt hàng/định hướng Nhật Bản)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('VTT',2025,'2025-2026',10500000,61500000,'VND/năm','10,5 - 61,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TDL',2025,'2025-2026',15000000,24000000,'VND/năm','15 - 24 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('KTA',2025,'2025-2026',15200000,18500000,'VND/năm','15,2 - 18,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DQT',2025,'2025-2026',15600000,17000000,'VND/năm','15,6 - 17 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DVH',2025,'2025-2026',17470000,44100000,'VND/năm','17,47 - 44,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('SDU',2025,'2025-2026',18000000,20000000,'VND/năm','18 - 20 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('CMC',2025,'2025-2026',21550000,23650000,'VND/năm','21,55 - 23,65 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('TDM',2025,'2025-2026',22800000,34690000,'VND/năm','22,8 - 34,69 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('KTD',2025,'2025-2026',27840000,37800000,'VND/năm','27,84 - 37,8 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DHV',2025,'2025-2026',33000000,33000000,'VND/năm','33 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('SIU',2025,'2025-2026',34300000,72000000,'VND/năm','34,3 - 72 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DNT',2025,'2025-2026',38130000,39360000,'VND/năm','38,13 - 39,36 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('VGU',2025,'2025-2026',42600000,45400000,'VND/năm','42,6 - 45,4 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('UKH',2025,'2025-2026',10400000,15170000,'VND/năm','10,4 - 15,17 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDK',2025,'2025-2026',25900000,36200000,'VND/năm','25,9 - 30,896 triệu (chuẩn); 26,3 triệu (PFIEV); 36,2 triệu (tiên tiến)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('VKU',2025,'2025-2026',16000000,18000000,'VND/năm','16 - 18 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDQ',2025,'2025-2026',27500000,40000000,'VND/năm','27,5 - 40 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDF',2025,'2025-2026',16900000,19500000,'VND/năm','16,9 - 19,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDS',2025,'2025-2026',14820000,17240000,'VND/năm','14,82 - 17,24 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DSK',2025,'2025-2026',15900000,25900000,'VND/năm','15,9 - 25,9 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDP',2025,'2025-2026',15000000,17500000,'VND/năm','15 - 17,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDY',2025,'2025-2026',16900000,31100000,'VND/năm','16,9 - 31,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DDV',2025,'2025-2026',31800000,48100000,'VND/năm','31,8 - 48,1 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DTC',2025,'2025-2026',16500000,16500000,'VND/năm','16,5 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DTE',2025,'2025-2026',16000000,57650000,'VND/năm','16 - 18 triệu (chuẩn); 56,78 - 57,65 triệu (bằng tiếng Anh)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DTN',2025,'2025-2026',14100000,28900000,'VND/năm','14,1 - 16,4 triệu (chuẩn); 28,9 triệu (tiên tiến)','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DTS',2025,'2025-2026',15900000,15900000,'VND/năm','15,9 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html'),
('DTY',2025,'2025-2026',43000000,59000000,'VND/năm','43 - 59 triệu','https://baolamdong.vn/tong-hop-hoc-phi-cac-truong-dai-hoc-2025-387872.html')
ON CONFLICT (ma_truong, nam)
DO UPDATE SET
    nam_hoc = EXCLUDED.nam_hoc,
    hoc_phi_min = EXCLUDED.hoc_phi_min,
    hoc_phi_max = EXCLUDED.hoc_phi_max,
    don_vi = EXCLUDED.don_vi,
    ghi_chu = EXCLUDED.ghi_chu,
    source_url = EXCLUDED.source_url;

-- QA
SELECT
    COUNT(*) AS so_truong_hoc_phi_2025,
    MIN(hoc_phi_min) AS hoc_phi_thap_nhat,
    MAX(hoc_phi_max) AS hoc_phi_cao_nhat
FROM public.hoc_phi
WHERE nam = 2025;

SELECT
    h.ma_truong,
    t.ten_truong,
    h.hoc_phi_min,
    h.hoc_phi_max,
    h.ghi_chu
FROM public.hoc_phi h
LEFT JOIN public.truong_dh t
  ON t.ma_tuyen_sinh = h.ma_truong
WHERE h.nam = 2025
  AND t.ma_truong IS NULL
ORDER BY h.ma_truong;
