-- UniAdmSys: chỉ tiêu tuyển sinh đại học chính quy 2025 - batch xác minh
-- Dữ liệu cấp TRƯỜNG. Không suy diễn chỉ tiêu theo ngành khi nguồn không công bố.
-- Nguồn ưu tiên: trang chính thức; phần còn lại từ trang tổng hợp đề án tuyển sinh 2025 của Tuyensinh247.
-- Chạy lại an toàn.

CREATE TABLE IF NOT EXISTS public.chi_tieu_tuyen_sinh (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

ALTER TABLE public.chi_tieu_tuyen_sinh
    ADD COLUMN IF NOT EXISTS ma_truong VARCHAR(20),
    ADD COLUMN IF NOT EXISTS nam SMALLINT,
    ADD COLUMN IF NOT EXISTS cap_do VARCHAR(20) DEFAULT 'truong',
    ADD COLUMN IF NOT EXISTS chi_tieu INTEGER,
    ADD COLUMN IF NOT EXISTS chi_tieu_min INTEGER,
    ADD COLUMN IF NOT EXISTS chi_tieu_max INTEGER,
    ADD COLUMN IF NOT EXISTS he_dao_tao TEXT DEFAULT 'Đại học chính quy',
    ADD COLUMN IF NOT EXISTS ghi_chu TEXT,
    ADD COLUMN IF NOT EXISTS source_type VARCHAR(30),
    ADD COLUMN IF NOT EXISTS source_url TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now();

DELETE FROM public.chi_tieu_tuyen_sinh
WHERE nam = 2025
  AND cap_do = 'truong';

INSERT INTO public.chi_tieu_tuyen_sinh (
    ma_truong,
    nam,
    chi_tieu,
    chi_tieu_min,
    chi_tieu_max,
    ghi_chu,
    source_type,
    source_url
)
VALUES
('QHT',2025,2435,2435,2435,'Trường ĐH Khoa học Tự nhiên - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHX',2025,2650,2650,2650,'Trường ĐH Khoa học Xã hội và Nhân văn - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHF',2025,2400,2400,2400,'Trường ĐH Ngoại ngữ - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHI',2025,4020,4020,4020,'Trường ĐH Công nghệ - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHE',2025,2500,2500,2500,'Trường ĐH Kinh tế - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHS',2025,1300,1300,1300,'Trường ĐH Giáo dục - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('VJU',2025,750,750,750,'Trường ĐH Việt Nhật - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHY',2025,720,720,720,'Trường ĐH Y Dược - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHL',2025,1100,1100,1100,'Trường ĐH Luật - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHQ',2025,1350,1350,1350,'Trường Quốc tế - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHD',2025,700,700,700,'Trường Quản trị và Kinh doanh - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHK',2025,1200,1200,1200,'Trường Khoa học liên ngành và Nghệ thuật - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('DKS',2025,850,850,850,'Đại học Kiểm sát Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DTP',2025,898,898,898,'Phân hiệu ĐH Thái Nguyên tại Lào Cai','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('HPU',2025,1164,1164,1164,'Đại học Quản lý và Công nghệ Hải Phòng','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('FBU',2025,1800,1800,1800,'Đại học Tài chính - Ngân hàng Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DTC',2025,3300,3300,3300,'Đại học CNTT và Truyền thông - ĐH Thái Nguyên','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DDF',2025,2260,2260,2260,'Đại học Ngoại ngữ - ĐH Đà Nẵng','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DHF',2025,1949,1949,1949,'Đại học Ngoại ngữ - ĐH Huế','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DLX',2025,2750,2750,2750,'Đại học Lao động - Xã hội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('HLU',2025,2000,2000,2000,'Đại học Hạ Long','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('PCH',2025,100,100,100,'Đại học Phòng cháy chữa cháy phía Bắc','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('CSH',2025,530,530,530,'Học viện Cảnh sát nhân dân','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('ANH',2025,540,540,540,'Học viện An ninh nhân dân','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DDP',2025,350,350,350,'Phân hiệu ĐH Đà Nẵng tại Kon Tum','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DDV',2025,610,610,610,'Viện Nghiên cứu và Đào tạo Việt - Anh, ĐH Đà Nẵng','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DSK',2025,1800,1800,1800,'Đại học Sư phạm Kỹ thuật - ĐH Đà Nẵng','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('HQT',2025,2200,2200,2200,'Học viện Ngoại giao','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('YDN',2025,1250,1250,1250,'Đại học Kỹ thuật Y Dược Đà Nẵng','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('GNT',2025,1670,1670,1670,'Đại học Sư phạm Nghệ thuật Trung ương','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('TDB',2025,1270,1270,1270,'Đại học Thể dục thể thao Bắc Ninh','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('MHN',2025,4140,4140,4140,'Đại học Mở Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DDL',2025,6800,6800,6800,'Đại học Điện lực','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('VHH',2025,1900,1900,1900,'Đại học Văn hóa Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('HNM',2025,2365,2365,2365,'Đại học Thủ đô Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DKK',2025,6800,6800,6800,'Đại học Kinh tế - Kỹ thuật Công nghiệp','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('THP',2025,3075,3075,3075,'Đại học Hải Phòng','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DQH',2025,600,600,600,'Học viện Kỹ thuật Quân sự - hệ dân sự','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('NHH',2025,3644,3644,3644,'Học viện Ngân hàng','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('CSS',2025,420,420,420,'Đại học Cảnh sát nhân dân','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('KCC',2025,1720,1720,1720,'Đại học Kỹ thuật - Công nghệ Cần Thơ','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DQT',2025,1320,1320,1320,'Đại học Quang Trung','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('TCT',2025,10500,10500,10500,'Đại học Cần Thơ','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DQN',2025,5800,5800,5800,'Đại học Quy Nhơn','official_doc','https://images.tuyensinh247.com/picture/2025/0421/dai-hoc-quy-nhon.pdf'),
('TSN',2025,3800,3800,3800,'Đại học Nha Trang','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('TBD',2025,NULL,1200,NULL,'Đại học Thái Bình Dương - nguồn ghi ''hơn 1.200 sinh viên''','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('HTC',2025,6320,6320,6320,'Học viện Tài chính','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DMT',2025,4780,4780,4780,'Đại học Tài nguyên và Môi trường Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('HCH',2025,4200,4200,4200,'Học viện Hành chính và Quản trị công','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DHS',2025,2300,2300,2300,'Đại học Sư phạm - ĐH Huế','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('TDD',2025,1928,1928,1928,'Đại học Thành Đô - tổng từ bảng chỉ tiêu 14 ngành/chương trình công bố','official','https://thanhdo.edu.vn/announcement-first-round-of-regular-university-admissions-2025');

CREATE UNIQUE INDEX IF NOT EXISTS idx_chi_tieu_truong_nam
ON public.chi_tieu_tuyen_sinh(ma_truong, nam, cap_do);

CREATE INDEX IF NOT EXISTS idx_chi_tieu_2025_lookup
ON public.chi_tieu_tuyen_sinh(nam, ma_truong);

-- QA 1: tổng quan
SELECT
    COUNT(*) AS so_truong_co_chi_tieu_2025,
    COUNT(*) FILTER (WHERE chi_tieu IS NOT NULL) AS so_truong_co_so_chinh_xac,
    COUNT(*) FILTER (WHERE chi_tieu IS NULL) AS so_truong_chi_co_khoang,
    SUM(chi_tieu) FILTER (WHERE chi_tieu IS NOT NULL) AS tong_chi_tieu_xac_minh
FROM public.chi_tieu_tuyen_sinh
WHERE nam = 2025
  AND cap_do = 'truong';

-- QA 2: phải ra 0 nếu tất cả mã trường đã có trong truong_dh
SELECT
    c.ma_truong,
    c.ghi_chu
FROM public.chi_tieu_tuyen_sinh c
LEFT JOIN public.truong_dh t
  ON t.ma_tuyen_sinh = c.ma_truong
WHERE c.nam = 2025
  AND c.cap_do = 'truong'
  AND t.ma_truong IS NULL
ORDER BY c.ma_truong;

-- QA 3: xem thử
SELECT
    c.ma_truong,
    t.ten_truong,
    c.chi_tieu,
    c.chi_tieu_min,
    c.chi_tieu_max,
    c.source_type
FROM public.chi_tieu_tuyen_sinh c
LEFT JOIN public.truong_dh t
  ON t.ma_tuyen_sinh = c.ma_truong
WHERE c.nam = 2025
  AND c.cap_do = 'truong'
ORDER BY COALESCE(c.chi_tieu, c.chi_tieu_min) DESC NULLS LAST
LIMIT 50;
