-- UniAdmSys: ALL-IN-ONE phương thức xét tuyển 2025
-- Nguồn: dữ liệu đã có trong public.diem_chuan_import_2025
-- Chạy lại an toàn: dữ liệu năm 2025 sẽ được thay mới.

CREATE TABLE IF NOT EXISTS public.phuong_thuc_xet_tuyen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

ALTER TABLE public.phuong_thuc_xet_tuyen
    ADD COLUMN IF NOT EXISTS ma_phuong_thuc VARCHAR(20),
    ADD COLUMN IF NOT EXISTS ma_truong VARCHAR(20),
    ADD COLUMN IF NOT EXISTS nam SMALLINT,
    ADD COLUMN IF NOT EXISTS ten_phuong_thuc TEXT,
    ADD COLUMN IF NOT EXISTS source_url TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now();

-- Chuẩn hóa whitespace trong staging
UPDATE public.diem_chuan_import_2025
SET phuong_thuc = regexp_replace(trim(phuong_thuc), '[[:space:]]+', ' ', 'g')
WHERE phuong_thuc IS NOT NULL;

-- Chạy lại không bị nhân đôi
DELETE FROM public.phuong_thuc_xet_tuyen
WHERE nam = 2025;

WITH src AS (
    SELECT DISTINCT
        s.ma_tuyen_sinh AS ma_truong,
        s.nam,
        regexp_replace(trim(s.phuong_thuc), '[[:space:]]+', ' ', 'g') AS ten_phuong_thuc,
        MIN(s.source_url) OVER (
            PARTITION BY
                s.ma_tuyen_sinh,
                s.nam,
                regexp_replace(trim(s.phuong_thuc), '[[:space:]]+', ' ', 'g')
        ) AS source_url
    FROM public.diem_chuan_import_2025 s
    WHERE s.nam = 2025
      AND NULLIF(trim(s.phuong_thuc), '') IS NOT NULL
)
INSERT INTO public.phuong_thuc_xet_tuyen (
    ma_phuong_thuc,
    ma_truong,
    nam,
    ten_phuong_thuc,
    source_url
)
SELECT DISTINCT
    LEFT(
        MD5(
            src.ma_truong || '|' ||
            src.nam::text || '|' ||
            src.ten_phuong_thuc
        ),
        20
    ) AS ma_phuong_thuc,
    src.ma_truong,
    src.nam,
    src.ten_phuong_thuc,
    src.source_url
FROM src;

-- Indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_ptxt_ma_phuong_thuc
ON public.phuong_thuc_xet_tuyen(ma_phuong_thuc);

CREATE INDEX IF NOT EXISTS idx_ptxt_truong_nam
ON public.phuong_thuc_xet_tuyen(ma_truong, nam);

-- Nếu ma_tuyen_sinh đang unique thì thêm FK; nếu đã có thì bỏ qua.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ptxt_ma_truong_fkey'
    ) THEN
        BEGIN
            ALTER TABLE public.phuong_thuc_xet_tuyen
            ADD CONSTRAINT ptxt_ma_truong_fkey
            FOREIGN KEY (ma_truong)
            REFERENCES public.truong_dh(ma_tuyen_sinh);
        EXCEPTION
            WHEN invalid_foreign_key THEN
                RAISE NOTICE 'Bỏ qua FK: truong_dh.ma_tuyen_sinh chưa có UNIQUE constraint.';
            WHEN datatype_mismatch THEN
                RAISE NOTICE 'Bỏ qua FK: kiểu dữ liệu ma_truong chưa khớp.';
        END;
    END IF;
END $$;

-- QA 1: số phương thức theo trường/năm
SELECT
    COUNT(*) AS so_ban_ghi_phuong_thuc_2025,
    COUNT(DISTINCT ma_truong) AS so_truong_co_phuong_thuc_2025,
    COUNT(DISTINCT ten_phuong_thuc) AS so_ten_phuong_thuc_khac_nhau
FROM public.phuong_thuc_xet_tuyen
WHERE nam = 2025;

-- QA 2: trường nào trong bảng phương thức không map được
SELECT DISTINCT
    p.ma_truong
FROM public.phuong_thuc_xet_tuyen p
LEFT JOIN public.truong_dh t
    ON t.ma_tuyen_sinh = p.ma_truong
WHERE p.nam = 2025
  AND t.ma_truong IS NULL
ORDER BY p.ma_truong;

-- QA 3: xem thử 30 dòng
SELECT
    p.ma_truong,
    t.ten_truong,
    p.ten_phuong_thuc
FROM public.phuong_thuc_xet_tuyen p
LEFT JOIN public.truong_dh t
    ON t.ma_tuyen_sinh = p.ma_truong
WHERE p.nam = 2025
ORDER BY p.ma_truong, p.ten_phuong_thuc
LIMIT 30;
