-- UniAdmSys: ALL-IN-ONE tổ hợp xét tuyển 2025
-- Nguồn: public.diem_chuan_import_2025.to_hop_xet_tuyen
-- Tạo 2 bảng mới, không đụng schema legacy public.to_hop / public.mon_to_hop.

CREATE TABLE IF NOT EXISTS public.to_hop_xet_tuyen (
    ma_to_hop VARCHAR(20) PRIMARY KEY,
    ten_to_hop TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.nganh_to_hop_xet_tuyen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_truong VARCHAR(20) NOT NULL,
    ma_nganh VARCHAR(20) NOT NULL,
    nam SMALLINT NOT NULL,
    ma_to_hop VARCHAR(20) NOT NULL,
    phuong_thuc TEXT,
    source_url TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

-- Chạy lại an toàn cho 2025
DELETE FROM public.nganh_to_hop_xet_tuyen
WHERE nam = 2025;

-- 1) Tách toàn bộ mã tổ hợp dạng A00, A01, B00, D01, X02...
WITH extracted AS (
    SELECT DISTINCT
        UPPER(m[1]) AS ma_to_hop
    FROM public.diem_chuan_import_2025 s
    CROSS JOIN LATERAL regexp_matches(
        COALESCE(s.to_hop_xet_tuyen, ''),
        '([A-Za-z]{1,3}[0-9]{2})',
        'g'
    ) AS m
    WHERE s.nam = 2025
)
INSERT INTO public.to_hop_xet_tuyen (
    ma_to_hop,
    ten_to_hop
)
SELECT
    ma_to_hop,
    ma_to_hop
FROM extracted
ON CONFLICT (ma_to_hop)
DO NOTHING;

-- 2) Map tổ hợp vào đúng trường + ngành + phương thức
WITH src AS (
    SELECT DISTINCT
        s.ma_tuyen_sinh AS ma_truong,
        n.ma_nganh,
        s.nam,
        UPPER(m[1]) AS ma_to_hop,
        NULLIF(
            regexp_replace(trim(s.phuong_thuc), '[[:space:]]+', ' ', 'g'),
            ''
        ) AS phuong_thuc,
        s.source_url
    FROM public.diem_chuan_import_2025 s
    JOIN public.truong_dh t
      ON t.ma_tuyen_sinh = s.ma_tuyen_sinh
    JOIN public.nganh n
      ON n.ma_truong = t.ma_truong
     AND regexp_replace(trim(n.ma_nganh_tuyen_sinh), '[[:space:]]+', ' ', 'g')
         =
         regexp_replace(trim(s.ma_nganh_tuyen_sinh), '[[:space:]]+', ' ', 'g')
     AND n.nam = 2025
    CROSS JOIN LATERAL regexp_matches(
        COALESCE(s.to_hop_xet_tuyen, ''),
        '([A-Za-z]{1,3}[0-9]{2})',
        'g'
    ) AS m
    WHERE s.nam = 2025
)
INSERT INTO public.nganh_to_hop_xet_tuyen (
    ma_truong,
    ma_nganh,
    nam,
    ma_to_hop,
    phuong_thuc,
    source_url
)
SELECT DISTINCT
    ma_truong,
    ma_nganh,
    nam,
    ma_to_hop,
    phuong_thuc,
    source_url
FROM src;

CREATE UNIQUE INDEX IF NOT EXISTS idx_nganh_to_hop_2025_unique
ON public.nganh_to_hop_xet_tuyen (
    ma_truong,
    ma_nganh,
    nam,
    ma_to_hop,
    COALESCE(phuong_thuc, '')
);

CREATE INDEX IF NOT EXISTS idx_nganh_to_hop_lookup
ON public.nganh_to_hop_xet_tuyen(ma_truong, ma_nganh, nam);

CREATE INDEX IF NOT EXISTS idx_nganh_to_hop_code
ON public.nganh_to_hop_xet_tuyen(ma_to_hop);

-- QA 1
SELECT
    (SELECT COUNT(*) FROM public.to_hop_xet_tuyen) AS so_ma_to_hop,
    COUNT(*) AS so_mapping_nganh_to_hop_2025,
    COUNT(DISTINCT ma_truong) AS so_truong_co_to_hop_2025,
    COUNT(DISTINCT ma_nganh) AS so_nganh_co_to_hop_2025
FROM public.nganh_to_hop_xet_tuyen
WHERE nam = 2025;

-- QA 2: staging có chuỗi tổ hợp nhưng không tách được mã chuẩn
SELECT DISTINCT
    s.to_hop_xet_tuyen
FROM public.diem_chuan_import_2025 s
WHERE s.nam = 2025
  AND NULLIF(trim(s.to_hop_xet_tuyen), '') IS NOT NULL
  AND NOT (
      COALESCE(s.to_hop_xet_tuyen, '') ~ '[A-Za-z]{1,3}[0-9]{2}'
  )
ORDER BY s.to_hop_xet_tuyen
LIMIT 100;

-- QA 3: xem thử dữ liệu
SELECT
    x.ma_truong,
    t.ten_truong,
    n.ten_nganh,
    x.ma_to_hop,
    x.phuong_thuc
FROM public.nganh_to_hop_xet_tuyen x
LEFT JOIN public.truong_dh t
  ON t.ma_tuyen_sinh = x.ma_truong
LEFT JOIN public.nganh n
  ON n.ma_nganh = x.ma_nganh
WHERE x.nam = 2025
ORDER BY x.ma_truong, n.ten_nganh, x.ma_to_hop
LIMIT 50;
