-- UniAdmSys: ALL-IN-ONE chỉ tiêu tuyển sinh 2025
-- Mục tiêu: chạy MỘT LẦN, tạo đủ 1 dòng cho TẤT CẢ trường đang có trong truong_dh.
-- Trường có số đã xác minh -> điền số; trường chưa có nguồn đủ chắc -> giữ NULL, KHÔNG bịa.
-- cap_do = 'truong' (chỉ tiêu cấp trường/cơ sở), he_dao_tao = 'Đại học chính quy'.
-- Có thể chạy lại an toàn.

BEGIN;

CREATE TABLE IF NOT EXISTS public.chi_tieu_tuyen_sinh (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

ALTER TABLE public.chi_tieu_tuyen_sinh
    ADD COLUMN IF NOT EXISTS ma_truong VARCHAR(20),
    ADD COLUMN IF NOT EXISTS nam SMALLINT,
    ADD COLUMN IF NOT EXISTS cap_do VARCHAR(20) DEFAULT 'truong',
    ADD COLUMN IF NOT EXISTS chi_tieu INTEGER,
    ADD COLUMN IF NOT EXISTS chi_tieu_min INTEGER,
    ADD COLUMN IF NOT EXISTS chi_tieu_max INTEGER,
    ADD COLUMN IF NOT EXISTS he_dao_tao TEXT DEFAULT 'Đại học chính quy',
    ADD COLUMN IF NOT EXISTS trang_thai VARCHAR(30) DEFAULT 'chua_xac_minh',
    ADD COLUMN IF NOT EXISTS ghi_chu TEXT,
    ADD COLUMN IF NOT EXISTS source_type VARCHAR(30),
    ADD COLUMN IF NOT EXISTS source_url TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now();

-- Dọn riêng dữ liệu cấp trường năm 2025 để rerun không duplicate.
DELETE FROM public.chi_tieu_tuyen_sinh
WHERE nam = 2025
  AND COALESCE(cap_do,'truong') = 'truong';

-- Seed ALL: mọi trường có mã tuyển sinh trong truong_dh đều có 1 dòng 2025.
INSERT INTO public.chi_tieu_tuyen_sinh (
    ma_truong, nam, cap_do, he_dao_tao, trang_thai, ghi_chu
)
SELECT DISTINCT
    trim(t.ma_tuyen_sinh),
    2025,
    'truong',
    'Đại học chính quy',
    'chua_xac_minh',
    'Chưa có số chỉ tiêu 2025 được xác minh đủ chắc trong bộ nguồn hiện tại'
FROM public.truong_dh t
WHERE NULLIF(trim(t.ma_tuyen_sinh),'') IS NOT NULL;

-- Fill các trường đã xác minh. Các mã không tồn tại trong truong_dh sẽ tự bị bỏ qua.
WITH verified (
    ma_truong, chi_tieu, chi_tieu_min, chi_tieu_max,
    ghi_chu, source_type, source_url
) AS (
    VALUES
('QHT',2435,2435,2435,'ĐH Khoa học Tự nhiên - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHX',2650,2650,2650,'ĐH Khoa học Xã hội và Nhân văn - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHF',2400,2400,2400,'ĐH Ngoại ngữ - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHI',4020,4020,4020,'ĐH Công nghệ - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHE',2500,2500,2500,'ĐH Kinh tế - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHS',1300,1300,1300,'ĐH Giáo dục - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('VJU',750,750,750,'ĐH Việt Nhật - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHY',720,720,720,'ĐH Y Dược - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHL',1100,1100,1100,'ĐH Luật - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHQ',1350,1350,1350,'Trường Quốc tế - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHD',700,700,700,'Trường Quản trị và Kinh doanh - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('QHK',1200,1200,1200,'Trường Khoa học liên ngành và Nghệ thuật - ĐHQGHN','official','https://vnu.edu.vn/huong-dan-thuc-hien-cong-tac-tuyen-sinh-dai-hoc-chinh-quy-nam-2025-post36704.html'),
('BKA',9680,9680,9680,'Đại học Bách khoa Hà Nội','official','https://ts.hust.edu.vn/tin-tuc/dhbk-ha-noi-cong-bo-phuong-an-tuyen-sinh-dai-hoc-chinh-quy-nam-2025'),
('KHA',8200,8200,8200,'Đại học Kinh tế Quốc dân - chỉ tiêu ĐH chính quy','official','https://login.neu.edu.vn/vi/tin-tuc-moi-nhat/hoi-nghi-pho-bien-thong-tin-tuyen-sinh-tap-huan-tu-van-tuyen-sinh-dai-hoc-chinh-quy-nam-2025'),
('QSB',5550,5550,5550,'ĐH Bách khoa - ĐHQG TPHCM','official','https://fme.hcmut.edu.vn/truong-dai-hoc-bach-khoa-tp-hcm-chi-xet-tuyen-2-phuong-thuc-lan-dau-tuyen-nganh-kinh-te.html'),
('QST',4455,4455,4455,'ĐH Khoa học Tự nhiên - ĐHQG TPHCM','official','https://fis.hcmus.edu.vn/truong-dai-hoc-khoa-hoc-tu-nhien-dhqg-hcm-cong-bo-thong-tin-tuyen-sinh-nam-2025/'),
('QSK',2700,2700,2700,'ĐH Kinh tế - Luật - ĐHQG TPHCM','official','https://tuyensinh.uel.edu.vn/thong-tin-tuyen-sinh-dai-hoc-chinh-quy/'),
('QSX',3949,3949,3949,'ĐH KHXH&NV - ĐHQG TPHCM; số công bố khi công bố điểm chuẩn 2025','official','https://hcmussh.edu.vn/bai-viet/cong-bo-diem-chuan-trung-tuyen-dai-hoc-chinh-quy'),
('YCT',2325,2325,2325,'ĐH Y Dược Cần Thơ - chỉ tính hệ đại học chính quy, không gồm liên thông','official','https://www.ctump.edu.vn/truong-dai-hoc-y-duoc-can-tho-tuyen-sinh-hon-2700-chi-tieu-nam-2025.html'),
('MTH',135,135,135,'ĐH Mỹ thuật Việt Nam','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DKS',850,850,850,'ĐH Kiểm sát Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DTP',898,898,898,'Phân hiệu ĐH Thái Nguyên tại Lào Cai','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('HPU',1164,1164,1164,'ĐH Quản lý và Công nghệ Hải Phòng','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DDA',6500,6500,6500,'ĐH Công nghệ Đông Á','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DCA',650,650,650,'ĐH Chu Văn An','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('FBU',1800,1800,1800,'ĐH Tài chính - Ngân hàng Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DFA',1000,1000,1000,'ĐH Tài chính - Quản trị Kinh doanh','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DTC',3300,3300,3300,'ĐH CNTT và Truyền thông - ĐH Thái Nguyên','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DDF',2260,2260,2260,'ĐH Ngoại ngữ - ĐH Đà Nẵng','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DHF',1949,1949,1949,'ĐH Ngoại ngữ - ĐH Huế','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('HGH',40,40,40,'Trường Sĩ quan Phòng hóa','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DLX',2750,2750,2750,'ĐH Lao động - Xã hội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('HLU',2000,2000,2000,'ĐH Hạ Long','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('NVH',150,150,150,'Học viện Âm nhạc Quốc gia Việt Nam','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('PCH',100,100,100,'ĐH Phòng cháy chữa cháy - phía Bắc, hệ CAND','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('PCH1',250,250,250,'ĐH Phòng cháy chữa cháy - hệ dân sự phía Bắc','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('CSH',530,530,530,'Học viện Cảnh sát nhân dân','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('ANH',540,540,540,'Học viện An ninh nhân dân','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('ANS',260,260,260,'ĐH An ninh nhân dân','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DDP',350,350,350,'Phân hiệu ĐH Đà Nẵng tại Kon Tum','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DDV',610,610,610,'Viện Nghiên cứu và Đào tạo Việt - Anh, ĐH Đà Nẵng','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DDY',NULL,550,650,'Trường Y Dược - ĐH Đà Nẵng; nguồn công bố khoảng 550-650','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DDS',2700,2700,2700,'ĐH Sư phạm - ĐH Đà Nẵng; nguồn ghi khoảng 2.700','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DSK',1800,1800,1800,'ĐH Sư phạm Kỹ thuật - ĐH Đà Nẵng','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('HQT',2200,2200,2200,'Học viện Ngoại giao','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('YDN',1250,1250,1250,'ĐH Kỹ thuật Y Dược Đà Nẵng','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('GNT',1670,1670,1670,'ĐH Sư phạm Nghệ thuật Trung ương','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('TDB',1270,1270,1270,'ĐH Thể dục thể thao Bắc Ninh','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('MHN',4140,4140,4140,'ĐH Mở Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DDL',6800,6800,6800,'ĐH Điện lực','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('VHH',1900,1900,1900,'ĐH Văn hóa Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('HNM',2365,2365,2365,'ĐH Thủ đô Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DKK',6800,6800,6800,'ĐH Kinh tế - Kỹ thuật Công nghiệp','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DDB',1700,1700,1700,'ĐH Thành Đông','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('THP',3075,3075,3075,'ĐH Hải Phòng','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('HFH',400,400,400,'Học viện Hậu cần - hệ dân sự; chỉ tiêu trình độ đại học','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DNH',200,200,200,'Học viện Khoa học Quân sự - hệ dân sự; chỉ tiêu trình độ đại học','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DQH',600,600,600,'Học viện Kỹ thuật Quân sự - hệ dân sự; chỉ tiêu trình độ đại học','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('NHH',3644,3644,3644,'Học viện Ngân hàng','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('CSS',420,420,420,'ĐH Cảnh sát nhân dân','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('KCC',1720,1720,1720,'ĐH Kỹ thuật - Công nghệ Cần Thơ','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DQT',1320,1320,1320,'ĐH Quang Trung','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('TCT',10500,10500,10500,'ĐH Cần Thơ','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DQN',5800,5800,5800,'ĐH Quy Nhơn','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('TSN',3800,3800,3800,'ĐH Nha Trang','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('TBD',NULL,1201,NULL,'ĐH Thái Bình Dương; nguồn ghi hơn 1.200 sinh viên','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('HTC',6320,6320,6320,'Học viện Tài chính','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DMT',4780,4780,4780,'ĐH Tài nguyên và Môi trường Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('HCH',4200,4200,4200,'Học viện Hành chính và Quản trị công','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DHS',2300,2300,2300,'ĐH Sư phạm - ĐH Huế','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('TDD',1928,1928,1928,'ĐH Thành Đô; tổng chỉ tiêu công bố','official','https://thanhdo.edu.vn/announcement-first-round-of-regular-university-admissions-2025'),
('SDU',NULL,1200,1600,'ĐH Sao Đỏ; nguồn công bố 1.200-1.600','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('ETU',2379,2379,2379,'ĐH Hòa Bình','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DTL',3000,3000,3000,'ĐH Thăng Long','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('NTU',1130,1130,1130,'ĐH Nguyễn Trãi','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('SPH',4995,4995,4995,'ĐH Sư phạm Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('LNH',2300,2300,2300,'ĐH Lâm nghiệp - cơ sở miền Bắc','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('GTA',6000,6000,6000,'ĐH Công nghệ Giao thông Vận tải','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DQU',1170,1170,1170,'ĐH Quảng Nam','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DVT',7500,7500,7500,'ĐH Trà Vinh','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('LPH',2650,2650,2650,'ĐH Luật Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('VGU',1075,1075,1075,'ĐH Việt Đức','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('TTG',1870,1870,1870,'ĐH Tiền Giang','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('LNS',1000,1000,1000,'Phân hiệu ĐH Lâm nghiệp tại Đồng Nai','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('NLS',5251,5251,5251,'ĐH Nông Lâm TPHCM','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DYD',1756,1756,1756,'ĐH Yersin Đà Lạt','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('LPS',4000,4000,4000,'ĐH Luật TPHCM','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('QSQ',2000,2000,2000,'ĐH Quốc tế - ĐHQG TPHCM','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('YDS',2576,2576,2576,'ĐH Y Dược TPHCM','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('MBS',5500,5500,5500,'ĐH Mở TPHCM','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('DCN',7990,7990,7990,'ĐH Công nghiệp Hà Nội','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html'),
('NTH',4150,4150,4150,'ĐH Ngoại thương - tổng toàn trường','aggregator','https://thi.tuyensinh247.com/danh-sach-truong-cong-bo-de-an-tuyen-sinh-2025-moi-nhat-c24a83942.html')
)
UPDATE public.chi_tieu_tuyen_sinh c
SET
    chi_tieu = v.chi_tieu,
    chi_tieu_min = v.chi_tieu_min,
    chi_tieu_max = v.chi_tieu_max,
    ghi_chu = v.ghi_chu,
    source_type = v.source_type,
    source_url = v.source_url,
    trang_thai = CASE
        WHEN v.chi_tieu IS NOT NULL THEN 'da_xac_minh'
        WHEN v.chi_tieu_min IS NOT NULL AND v.chi_tieu_max IS NOT NULL THEN 'khoang_xac_minh'
        WHEN v.chi_tieu_min IS NOT NULL THEN 'toi_thieu_xac_minh'
        ELSE 'chua_xac_minh'
    END
FROM verified v
WHERE c.nam = 2025
  AND c.cap_do = 'truong'
  AND c.ma_truong = v.ma_truong;

-- Index cho truy vấn AI/API.
CREATE INDEX IF NOT EXISTS idx_chi_tieu_2025_lookup
ON public.chi_tieu_tuyen_sinh(nam, ma_truong);

CREATE INDEX IF NOT EXISTS idx_chi_tieu_status
ON public.chi_tieu_tuyen_sinh(nam, trang_thai);

COMMIT;

-- =========================
-- QA CUỐI - CHỈ CẦN NHÌN KẾT QUẢ NÀY
-- =========================
SELECT
    (SELECT COUNT(DISTINCT ma_tuyen_sinh)
       FROM public.truong_dh
      WHERE NULLIF(trim(ma_tuyen_sinh),'') IS NOT NULL) AS tong_truong_trong_db,
    COUNT(*) AS so_dong_chi_tieu_2025,
    COUNT(*) FILTER (WHERE trang_thai = 'da_xac_minh') AS co_so_chinh_xac,
    COUNT(*) FILTER (WHERE trang_thai = 'khoang_xac_minh') AS co_khoang,
    COUNT(*) FILTER (WHERE trang_thai = 'toi_thieu_xac_minh') AS co_muc_toi_thieu,
    COUNT(*) FILTER (WHERE trang_thai = 'chua_xac_minh') AS chua_xac_minh,
    ROUND(
        100.0 * COUNT(*) FILTER (WHERE trang_thai <> 'chua_xac_minh')
        / NULLIF(COUNT(*),0),
        2
    ) AS coverage_percent
FROM public.chi_tieu_tuyen_sinh
WHERE nam = 2025
  AND cap_do = 'truong';

-- Check duplicate: phải ra 0 rows.
SELECT ma_truong, nam, cap_do, COUNT(*) AS so_dong
FROM public.chi_tieu_tuyen_sinh
WHERE nam = 2025
  AND cap_do = 'truong'
GROUP BY ma_truong, nam, cap_do
HAVING COUNT(*) > 1;

-- Danh sách chưa xác minh để sau này bổ sung nguồn mà KHÔNG làm mất coverage.
SELECT
    c.ma_truong,
    t.ten_truong,
    c.trang_thai
FROM public.chi_tieu_tuyen_sinh c
LEFT JOIN public.truong_dh t
  ON t.ma_tuyen_sinh = c.ma_truong
WHERE c.nam = 2025
  AND c.cap_do = 'truong'
  AND c.trang_thai = 'chua_xac_minh'
ORDER BY t.ten_truong NULLS LAST, c.ma_truong;
